import type { TSchema } from "@sinclair/typebox";

import { AgentCommandV1 } from "./agent-command.js";
import { AgentWorldModelEnvelopeV1, AgentWorldModelSnapshotV1 } from "./agent-world-model.js";
import { AntiCheatReportV1, ViolationKindV1 } from "./anticheat.js";
import { ArmorDurabilityChangedV1 } from "./armor-event.js";
import {
  AudioEventV1,
  PlaySoundRecipeEventV1,
  SoundRecipeV1,
  StopSoundRecipeEventV1,
} from "./audio-event.js";
import {
  AlchemyContaminationLevelV1,
  AlchemyInsightV1,
  AlchemyInterventionResultV1,
  AlchemyInterventionV1,
  AlchemyOutcomeBucket,
  AlchemyRecipeEntryV1,
  AlchemySessionEndV1,
  AlchemySessionStartV1,
  AlchemyStageHintV1,
} from "./alchemy.js";
import { BotanyEcologySnapshotV1 } from "./botany.js";
import { BiographyEntryV1, HeartDemonOutcomeV1 } from "./biography.js";
import { BreakthroughEventV1 } from "./breakthrough-event.js";
import { ChatMessageV1, ChatSignal } from "./chat-message.js";
import {
  ClientNarrationPayloadV1,
  ClientPayloadV1,
  EventAlertPayloadV1,
  HeartbeatPayloadV1,
  PlayerStatePayloadV1,
  WelcomePayloadV1,
  ZoneInfoPayloadV1,
} from "./client-payload.js";
import {
  AlchemyFeedSlotRequestV1,
  AlchemyIgniteRequestV1,
  AlchemyInterventionRequestV1,
  AlchemyLearnRecipeRequestV1,
  AlchemyOpenFurnaceRequestV1,
  AlchemyTakeBackRequestV1,
  AlchemyTakePillRequestV1,
  AlchemyTurnPageRequestV1,
  BotanyHarvestRequestV1,
  BreakthroughRequestV1,
  AbortTribulationRequestV1,
  CancelExtractRequestV1,
  CoffinOpenRequestV1,
  CombatCreateNewCharacterRequestV1,
  CombatReincarnateRequestV1,
  CombatTerminateRequestV1,
  ClientRequestV1,
  DuoSheRequestV1,
  QiColorInspectRequestV1,
  EquipFalseSkinRequestV1,
  ForgeFalseSkinRequestV1,
  ForgeRequestV1,
  HeartDemonDecisionRequestV1,
  ForgeStartSessionRequestV1,
  ForgeTemperingHitRequestV1,
  ForgeInscriptionScrollRequestV1,
  ForgeConsecrationInjectRequestV1,
  ForgeStepAdvanceRequestV1,
  ForgeBlueprintTurnPageRequestV1,
  ForgeLearnBlueprintRequestV1,
  ForgeStationPlaceRequestV1,
  InsightDecisionRequestV1,
  MineralProbeRequestV1,
  QuickSlotBindRequestV1,
  SetMeridianTargetRequestV1,
  SkillBarBindRequestV1,
  SkillBarCastRequestV1,
  StartDuXuRequestV1,
  SparringInviteResponseRequestV1,
  StartExtractRequestV1,
  TradeOfferRequestV1,
  TradeOfferResponseRequestV1,
  SelfAntidoteRequestV1,
  UseQuickSlotRequestV1,
  UseLifeCoreRequestV1,
  ZhenfaDisarmRequestV1,
  ZhenfaPlaceRequestV1,
  ZhenfaTriggerRequestV1,
} from "./client-request.js";
import {
  SkillBarConfigV1,
  SkillBarEntryV1,
  TechniquesSnapshotV1,
} from "./combat-hud.js";
import { CombatRealtimeEventV1, CombatSummaryV1 } from "./combat-event.js";
import {
  AntidoteResultEventV1,
  AntidoteResultV1,
  DuguObfuscationStateV1,
  DuguPoisonProgressEventV1,
  DuguPoisonStateV1,
  DuguRevealedEventV1,
} from "./dugu.js";
import { CultivationDeathV1 } from "./cultivation-death.js";
import { DeathInsightRequestV1 } from "./death-insight.js";
import {
  DeathRegistryV1,
  AgingEventV1,
  DeceasedIndexEntryV1,
  DeceasedSnapshotV1,
  DuoSheEventV1,
  LifespanEventV1,
  LifespanCapByRealmV1,
  LifespanComponentV1,
  LifespanPreviewV1,
  RebirthChanceInputV1,
  RebirthChanceResultV1,
} from "./death-lifecycle.js";
import {
  ExtractAbortedV1,
  ExtractCompletedV1,
  ExtractFailedV1,
  ExtractProgressV1,
  ExtractStartedV1,
  RiftPortalRemovedV1,
  RiftPortalStateV1,
  TsyCollapseStartedIpcV1,
} from "./extract-v1.js";
import { ForgeEventV1 } from "./forge-event.js";
import {
  ForgeOutcomePayloadV1,
  ForgeStartPayloadV1,
} from "./forge-bridge.js";
import {
  ForgeBlueprintBookDataV1,
  ForgeBlueprintEntryV1,
  ForgeOutcomeBucket,
  ForgeOutcomeDataV1,
  ForgeSessionDataV1,
  ForgeStep,
  ForgeStepState,
  TemperBeat,
  WeaponForgeStationDataV1,
  WeaponTier,
} from "./forge.js";
import { InventoryEventV1, InventorySnapshotV1 } from "./inventory.js";
import { InsightOfferV1 } from "./insight-offer.js";
import { InsightRequestV1 } from "./insight-request.js";
import {
  HeartDemonOfferDraftV1,
  HeartDemonPregenRequestV1,
} from "./heart-demon.js";
import { NarrationV1 } from "./narration.js";
import {
  DuXuOutcomeV1,
  DuXuResultV1,
  TribulationEventV1,
  TribulationKindV1,
  TribulationPhaseV1,
} from "./tribulation.js";
import {
  FactionEventKindV1,
  FactionEventV1,
  FactionIdV1,
  NpcArchetypeV1,
  NpcDeathCauseV1,
  NpcDeathV1,
  NpcSpawnedV1,
  NpcSpawnSourceV1,
} from "./npc.js";
import {
  PoiNoviceKindV1,
  PoiSpawnedEventV1,
  TrespassEventV1,
} from "./poi-novice.js";
import {
  PseudoVeinDissipateEventV1,
  PseudoVeinSeasonV1,
  PseudoVeinSnapshotV1,
} from "./pseudo-vein.js";
import {
  ZongCoreActivationV1,
  ZongmenOriginIdV1,
} from "./zong-formation.js";
import { FogShapeV1, RealmVisionParamsV1 } from "./realm-vision.js";
import {
  ServerDataAlchemyContaminationV1,
  ServerDataAlchemyFurnaceV1,
  ServerDataAlchemyOutcomeForecastV1,
  ServerDataAlchemyOutcomeResolvedV1,
  ServerDataAlchemyRecipeBookV1,
  ServerDataAlchemySessionV1,
  ServerDataDeathScreenV1,
  ServerDataTerminateScreenV1,
  ServerDataBotanyHarvestProgressV1,
  BotanyModelOverlayV1,
  BotanyPlantV2RenderProfileV1,
  ServerDataBotanyPlantV2RenderProfilesV1,
  ServerDataLumberProgressV1,
  ServerDataBotanySkillV1,
  ServerDataExtractAbortedV1,
  ServerDataExtractCompletedV1,
  ServerDataExtractFailedV1,
  ServerDataExtractProgressV1,
  ServerDataExtractStartedV1,
  ServerDataRiftPortalRemovedV1,
  ServerDataRiftPortalStateV1,
  ServerDataSkillCapChangedV1,
  ServerDataSkillBarConfigV1,
  ServerDataSkillLvUpV1,
  ServerDataSkillSnapshotV1,
  ServerDataSkillScrollUsedV1,
  ServerDataSkillXpGainV1,
  ServerDataAscensionQuotaV1,
  ServerDataTechniquesSnapshotV1,
  ServerDataTribulationStateV1,
  ServerDataTribulationBroadcastV1,
  ServerDataTreasureEquippedV1,
  ServerDataFalseSkinStateV1,
  ServerDataVortexStateV1,
  ServerDataCarrierStateV1,
  ServerDataDuguPoisonStateV1,
  ServerDataTsyCollapseStartedIpcV1,
  ServerDataV1,
  ServerDataWeaponBrokenV1,
  ServerDataWeaponEquippedV1,
  ServerDataForgeStationV1,
  ServerDataForgeSessionV1,
  ServerDataForgeOutcomeV1,
  ServerDataForgeBlueprintBookV1,
  HeartDemonOfferChoiceV1,
  ServerDataHeartDemonOfferV1,
  ServerDataSocialAnonymityV1,
  ServerDataSocialExposureV1,
  ServerDataSocialPactV1,
  ServerDataSocialFeudV1,
  ServerDataSocialRenownDeltaV1,
  ServerDataNicheGuardianBrokenV1,
  ServerDataNicheGuardianFatigueV1,
  ServerDataNicheIntrusionV1,
  ServerDataSparringInviteV1,
  ServerDataTradeOfferV1,
  ServerDataRealmVisionParamsV1,
  ServerDataSpiritualSenseTargetsV1,
  BurstMeridianEventV1,
  QiColorObservedV1,
  TreasureEquippedV1,
  TreasureViewV1,
  WeaponBrokenV1,
  WeaponEquippedV1,
  WeaponViewV1,
} from "./server-data.js";
import {
  CarrierChargedEventV1,
  CarrierImpactEventV1,
  CarrierStateV1,
  ProjectileDespawnedEventV1,
} from "./combat-carrier.js";
import {
  FalseSkinKindV1,
  FalseSkinStateV1,
  ShedEventV1,
} from "./tuike.js";
import {
  ProjectileQiDrainedEventV1,
  VortexBackfireEventV1,
  VortexFieldStateV1,
} from "./woliu.js";
import {
  DeceasedExposureSnapshotV1,
  DeceasedRenownSnapshotV1,
  DeceasedSocialSnapshotV1,
  ExposureKindV1,
  FactionMembershipSnapshotV1,
  GuardianKindV1,
  NicheGuardianBrokenV1,
  NicheGuardianFatigueV1,
  NicheIntrusionEventV1,
  PlayerSocialSnapshotV1,
  RelationshipKindV1,
  RelationshipSnapshotV1,
  RenownSnapshotV1,
  RenownTagV1,
  SocialAnonymityPayloadV1,
  SocialExposureEventV1,
  SocialFeudEventV1,
  SocialPactEventV1,
  SocialRemoteIdentityV1,
  SocialRenownDeltaV1,
  SparringInvitePayloadV1,
  SpiritNicheActivateGuardianV1,
  TradeItemSummaryV1,
  TradeOfferPayloadV1,
} from "./social.js";
import {
  SenseEntryV1,
  SenseKindV1,
  SpiritualSenseTargetsV1,
} from "./spiritual-sense.js";
import {
  CoffinOpenedV1,
  TutorialHookEventV1,
  TutorialHookV1,
} from "./spawn-tutorial.js";
import {
  DeathInsightSpiritEyeV1,
  SpiritEyeCoordinateNoteV1,
  SpiritEyeDiscoveredV1,
  SpiritEyeMigrateReasonV1,
  SpiritEyeMigrateV1,
  SpiritEyePositionV1,
  SpiritEyeUsedForBreakthroughV1,
} from "./spirit-eye.js";
import {
  StyleBalanceTelemetryEventV1,
  StyleTelemetryColorSnapshotV1,
} from "./style-balance.js";
import {
  DaoxiangSpawnedV1,
  TsyCollapseCompletedV1,
  TsyCollapseStartedV1,
  TsyCorpseSpawnEventV1,
  TsyEnterEventV1,
  TsyExitEventV1,
  TsyZoneActivatedV1,
} from "./tsy.js";
import {
  TsyHostileArchetypeV1,
  TsyNpcSpawnedV1,
  TsySentinelPhaseChangedV1,
} from "./tsy-hostile-v1.js";
import {
  CancelSearchRequestV1,
  ContainerStateV1,
  SearchAbortedV1,
  SearchCompletedV1,
  SearchProgressV1,
  SearchStartedV1,
  StartSearchRequestV1,
} from "./container-interaction.js";
import { VfxEventV1 } from "./vfx-event.js";
import { WorldStateV1 } from "./world-state.js";

export const SCHEMA_REGISTRY = {
  worldStateV1: WorldStateV1,
  agentCommandV1: AgentCommandV1,
  agentWorldModelEnvelopeV1: AgentWorldModelEnvelopeV1,
  agentWorldModelSnapshotV1: AgentWorldModelSnapshotV1,
  narrationV1: NarrationV1,
  npcArchetypeV1: NpcArchetypeV1,
  npcSpawnSourceV1: NpcSpawnSourceV1,
  npcDeathCauseV1: NpcDeathCauseV1,
  factionIdV1: FactionIdV1,
  factionEventKindV1: FactionEventKindV1,
  npcSpawnedV1: NpcSpawnedV1,
  npcDeathV1: NpcDeathV1,
  poiNoviceKindV1: PoiNoviceKindV1,
  poiSpawnedEventV1: PoiSpawnedEventV1,
  trespassEventV1: TrespassEventV1,
  factionEventV1: FactionEventV1,
  pseudoVeinSeasonV1: PseudoVeinSeasonV1,
  pseudoVeinSnapshotV1: PseudoVeinSnapshotV1,
  pseudoVeinDissipateEventV1: PseudoVeinDissipateEventV1,
  zongmenOriginIdV1: ZongmenOriginIdV1,
  zongCoreActivationV1: ZongCoreActivationV1,
  chatMessageV1: ChatMessageV1,
  chatSignal: ChatSignal,
  inventorySnapshotV1: InventorySnapshotV1,
  inventoryEventV1: InventoryEventV1,
  serverDataV1: ServerDataV1,
  clientPayloadV1: ClientPayloadV1,
  clientPayloadWelcomeV1: WelcomePayloadV1,
  clientPayloadHeartbeatV1: HeartbeatPayloadV1,
  clientPayloadNarrationV1: ClientNarrationPayloadV1,
  clientPayloadZoneInfoV1: ZoneInfoPayloadV1,
  clientPayloadEventAlertV1: EventAlertPayloadV1,
  clientPayloadPlayerStateV1: PlayerStatePayloadV1,
  insightRequestV1: InsightRequestV1,
  insightOfferV1: InsightOfferV1,
  heartDemonPregenRequestV1: HeartDemonPregenRequestV1,
  heartDemonOfferDraftV1: HeartDemonOfferDraftV1,
  breakthroughEventV1: BreakthroughEventV1,
  forgeEventV1: ForgeEventV1,
  biographyEntryV1: BiographyEntryV1,
  cultivationDeathV1: CultivationDeathV1,
  deathInsightRequestV1: DeathInsightRequestV1,
  deathRegistryV1: DeathRegistryV1,
  deceasedIndexEntryV1: DeceasedIndexEntryV1,
  deceasedSnapshotV1: DeceasedSnapshotV1,
  heartDemonOutcomeV1: HeartDemonOutcomeV1,
  lifespanEventV1: LifespanEventV1,
  agingEventV1: AgingEventV1,
  duoSheEventV1: DuoSheEventV1,
  lifespanCapByRealmV1: LifespanCapByRealmV1,
  lifespanComponentV1: LifespanComponentV1,
  lifespanPreviewV1: LifespanPreviewV1,
  rebirthChanceInputV1: RebirthChanceInputV1,
  rebirthChanceResultV1: RebirthChanceResultV1,
  combatRealtimeEventV1: CombatRealtimeEventV1,
  combatSummaryV1: CombatSummaryV1,
  styleTelemetryColorSnapshotV1: StyleTelemetryColorSnapshotV1,
  styleBalanceTelemetryEventV1: StyleBalanceTelemetryEventV1,
  violationKindV1: ViolationKindV1,
  antiCheatReportV1: AntiCheatReportV1,
  armorDurabilityChangedV1: ArmorDurabilityChangedV1,
  tribulationKindV1: TribulationKindV1,
  tribulationPhaseV1: TribulationPhaseV1,
  duXuOutcomeV1: DuXuOutcomeV1,
  duXuResultV1: DuXuResultV1,
  tribulationEventV1: TribulationEventV1,
  audioEventV1: AudioEventV1,
  playSoundRecipeEventV1: PlaySoundRecipeEventV1,
  stopSoundRecipeEventV1: StopSoundRecipeEventV1,
  soundRecipeV1: SoundRecipeV1,
  clientRequestV1: ClientRequestV1,
  clientRequestSetMeridianTargetV1: SetMeridianTargetRequestV1,
  clientRequestBreakthroughV1: BreakthroughRequestV1,
  clientRequestStartDuXuV1: StartDuXuRequestV1,
  clientRequestAbortTribulationV1: AbortTribulationRequestV1,
  clientRequestHeartDemonDecisionV1: HeartDemonDecisionRequestV1,
  clientRequestForgeV1: ForgeRequestV1,
  clientRequestInsightDecisionV1: InsightDecisionRequestV1,
  clientRequestDuoSheV1: DuoSheRequestV1,
  clientRequestQiColorInspectV1: QiColorInspectRequestV1,
  clientRequestEquipFalseSkinV1: EquipFalseSkinRequestV1,
  clientRequestForgeFalseSkinV1: ForgeFalseSkinRequestV1,
  clientRequestUseLifeCoreV1: UseLifeCoreRequestV1,
  clientRequestMineralProbeV1: MineralProbeRequestV1,
  clientRequestBotanyHarvestV1: BotanyHarvestRequestV1,
  clientRequestCombatReincarnateV1: CombatReincarnateRequestV1,
  clientRequestCombatTerminateV1: CombatTerminateRequestV1,
  clientRequestCombatCreateNewCharacterV1: CombatCreateNewCharacterRequestV1,
  clientRequestUseQuickSlotV1: UseQuickSlotRequestV1,
  clientRequestQuickSlotBindV1: QuickSlotBindRequestV1,
  clientRequestSkillBarCastV1: SkillBarCastRequestV1,
  clientRequestSkillBarBindV1: SkillBarBindRequestV1,
  clientRequestCoffinOpenV1: CoffinOpenRequestV1,
  clientRequestSparringInviteResponseV1: SparringInviteResponseRequestV1,
  clientRequestTradeOfferV1: TradeOfferRequestV1,
  clientRequestTradeOfferResponseV1: TradeOfferResponseRequestV1,
  clientRequestSelfAntidoteV1: SelfAntidoteRequestV1,
  clientRequestZhenfaPlaceV1: ZhenfaPlaceRequestV1,
  clientRequestZhenfaTriggerV1: ZhenfaTriggerRequestV1,
  clientRequestZhenfaDisarmV1: ZhenfaDisarmRequestV1,
  clientRequestStartExtractV1: StartExtractRequestV1,
  clientRequestCancelExtractV1: CancelExtractRequestV1,
  serverDataBotanyHarvestProgressV1: ServerDataBotanyHarvestProgressV1,
  botanyModelOverlayV1: BotanyModelOverlayV1,
  botanyPlantV2RenderProfileV1: BotanyPlantV2RenderProfileV1,
  serverDataBotanyPlantV2RenderProfilesV1: ServerDataBotanyPlantV2RenderProfilesV1,
  serverDataLumberProgressV1: ServerDataLumberProgressV1,
  serverDataBotanySkillV1: ServerDataBotanySkillV1,
  serverDataDeathScreenV1: ServerDataDeathScreenV1,
  serverDataTerminateScreenV1: ServerDataTerminateScreenV1,
  serverDataTribulationStateV1: ServerDataTribulationStateV1,
  serverDataTribulationBroadcastV1: ServerDataTribulationBroadcastV1,
  serverDataAscensionQuotaV1: ServerDataAscensionQuotaV1,
  heartDemonOfferChoiceV1: HeartDemonOfferChoiceV1,
  serverDataHeartDemonOfferV1: ServerDataHeartDemonOfferV1,
  serverDataSkillXpGainV1: ServerDataSkillXpGainV1,
  serverDataSkillLvUpV1: ServerDataSkillLvUpV1,
  serverDataSkillCapChangedV1: ServerDataSkillCapChangedV1,
  serverDataSkillSnapshotV1: ServerDataSkillSnapshotV1,
  serverDataSkillScrollUsedV1: ServerDataSkillScrollUsedV1,
  burstMeridianEventV1: BurstMeridianEventV1,
  qiColorObservedV1: QiColorObservedV1,
  skillBarEntryV1: SkillBarEntryV1,
  skillBarConfigV1: SkillBarConfigV1,
  techniquesSnapshotV1: TechniquesSnapshotV1,
  serverDataSkillBarConfigV1: ServerDataSkillBarConfigV1,
  serverDataTechniquesSnapshotV1: ServerDataTechniquesSnapshotV1,
  weaponViewV1: WeaponViewV1,
  weaponEquippedV1: WeaponEquippedV1,
  weaponBrokenV1: WeaponBrokenV1,
  treasureViewV1: TreasureViewV1,
  treasureEquippedV1: TreasureEquippedV1,
  serverDataWeaponEquippedV1: ServerDataWeaponEquippedV1,
  serverDataWeaponBrokenV1: ServerDataWeaponBrokenV1,
  serverDataTreasureEquippedV1: ServerDataTreasureEquippedV1,
  vortexFieldStateV1: VortexFieldStateV1,
  vortexBackfireEventV1: VortexBackfireEventV1,
  projectileQiDrainedEventV1: ProjectileQiDrainedEventV1,
  serverDataVortexStateV1: ServerDataVortexStateV1,
  duguPoisonStateV1: DuguPoisonStateV1,
  duguPoisonProgressEventV1: DuguPoisonProgressEventV1,
  duguObfuscationStateV1: DuguObfuscationStateV1,
  antidoteResultV1: AntidoteResultV1,
  antidoteResultEventV1: AntidoteResultEventV1,
  duguRevealedEventV1: DuguRevealedEventV1,
  serverDataDuguPoisonStateV1: ServerDataDuguPoisonStateV1,
  carrierStateV1: CarrierStateV1,
  carrierChargedEventV1: CarrierChargedEventV1,
  carrierImpactEventV1: CarrierImpactEventV1,
  projectileDespawnedEventV1: ProjectileDespawnedEventV1,
  serverDataCarrierStateV1: ServerDataCarrierStateV1,
  falseSkinKindV1: FalseSkinKindV1,
  falseSkinStateV1: FalseSkinStateV1,
  shedEventV1: ShedEventV1,
  serverDataFalseSkinStateV1: ServerDataFalseSkinStateV1,
  botanyEcologySnapshotV1: BotanyEcologySnapshotV1,
  vfxEventV1: VfxEventV1,
  // plan-social-v1 §7
  exposureKindV1: ExposureKindV1,
  relationshipKindV1: RelationshipKindV1,
  guardianKindV1: GuardianKindV1,
  renownTagV1: RenownTagV1,
  relationshipSnapshotV1: RelationshipSnapshotV1,
  renownSnapshotV1: RenownSnapshotV1,
  factionMembershipSnapshotV1: FactionMembershipSnapshotV1,
  playerSocialSnapshotV1: PlayerSocialSnapshotV1,
  deceasedRenownSnapshotV1: DeceasedRenownSnapshotV1,
  deceasedExposureSnapshotV1: DeceasedExposureSnapshotV1,
  deceasedSocialSnapshotV1: DeceasedSocialSnapshotV1,
  socialRemoteIdentityV1: SocialRemoteIdentityV1,
  socialAnonymityPayloadV1: SocialAnonymityPayloadV1,
  socialExposureEventV1: SocialExposureEventV1,
  socialPactEventV1: SocialPactEventV1,
  socialFeudEventV1: SocialFeudEventV1,
  socialRenownDeltaV1: SocialRenownDeltaV1,
  spiritNicheActivateGuardianV1: SpiritNicheActivateGuardianV1,
  nicheIntrusionEventV1: NicheIntrusionEventV1,
  nicheGuardianFatigueV1: NicheGuardianFatigueV1,
  nicheGuardianBrokenV1: NicheGuardianBrokenV1,
  sparringInvitePayloadV1: SparringInvitePayloadV1,
  tradeItemSummaryV1: TradeItemSummaryV1,
  tradeOfferPayloadV1: TradeOfferPayloadV1,
  serverDataSocialAnonymityV1: ServerDataSocialAnonymityV1,
  serverDataSocialExposureV1: ServerDataSocialExposureV1,
  serverDataSocialPactV1: ServerDataSocialPactV1,
  serverDataSocialFeudV1: ServerDataSocialFeudV1,
  serverDataSocialRenownDeltaV1: ServerDataSocialRenownDeltaV1,
  serverDataNicheIntrusionV1: ServerDataNicheIntrusionV1,
  serverDataNicheGuardianFatigueV1: ServerDataNicheGuardianFatigueV1,
  serverDataNicheGuardianBrokenV1: ServerDataNicheGuardianBrokenV1,
  serverDataSparringInviteV1: ServerDataSparringInviteV1,
  serverDataTradeOfferV1: ServerDataTradeOfferV1,
  fogShapeV1: FogShapeV1,
  realmVisionParamsV1: RealmVisionParamsV1,
  serverDataRealmVisionParamsV1: ServerDataRealmVisionParamsV1,
  senseKindV1: SenseKindV1,
  senseEntryV1: SenseEntryV1,
  spiritualSenseTargetsV1: SpiritualSenseTargetsV1,
  spiritEyePositionV1: SpiritEyePositionV1,
  spiritEyeMigrateReasonV1: SpiritEyeMigrateReasonV1,
  spiritEyeMigrateV1: SpiritEyeMigrateV1,
  spiritEyeDiscoveredV1: SpiritEyeDiscoveredV1,
  spiritEyeUsedForBreakthroughV1: SpiritEyeUsedForBreakthroughV1,
  spiritEyeCoordinateNoteV1: SpiritEyeCoordinateNoteV1,
  deathInsightSpiritEyeV1: DeathInsightSpiritEyeV1,
  serverDataSpiritualSenseTargetsV1: ServerDataSpiritualSenseTargetsV1,
  tutorialHookV1: TutorialHookV1,
  tutorialHookEventV1: TutorialHookEventV1,
  coffinOpenedV1: CoffinOpenedV1,
  // 炼丹 (plan-alchemy-v1 §4)
  alchemyOutcomeBucket: AlchemyOutcomeBucket,
  alchemyInterventionV1: AlchemyInterventionV1,
  alchemyRecipeEntryV1: AlchemyRecipeEntryV1,
  alchemyStageHintV1: AlchemyStageHintV1,
  alchemyContaminationLevelV1: AlchemyContaminationLevelV1,
  alchemySessionStartV1: AlchemySessionStartV1,
  alchemySessionEndV1: AlchemySessionEndV1,
  alchemyInterventionResultV1: AlchemyInterventionResultV1,
  alchemyInsightV1: AlchemyInsightV1,
  serverDataAlchemyFurnaceV1: ServerDataAlchemyFurnaceV1,
  serverDataAlchemySessionV1: ServerDataAlchemySessionV1,
  serverDataAlchemyOutcomeForecastV1: ServerDataAlchemyOutcomeForecastV1,
  serverDataAlchemyOutcomeResolvedV1: ServerDataAlchemyOutcomeResolvedV1,
  serverDataAlchemyRecipeBookV1: ServerDataAlchemyRecipeBookV1,
  serverDataAlchemyContaminationV1: ServerDataAlchemyContaminationV1,
  clientRequestAlchemyOpenFurnaceV1: AlchemyOpenFurnaceRequestV1,
  clientRequestAlchemyFeedSlotV1: AlchemyFeedSlotRequestV1,
  clientRequestAlchemyTakeBackV1: AlchemyTakeBackRequestV1,
  clientRequestAlchemyIgniteV1: AlchemyIgniteRequestV1,
  clientRequestAlchemyInterventionV1: AlchemyInterventionRequestV1,
  clientRequestAlchemyTurnPageV1: AlchemyTurnPageRequestV1,
  clientRequestAlchemyLearnRecipeV1: AlchemyLearnRecipeRequestV1,
  clientRequestAlchemyTakePillV1: AlchemyTakePillRequestV1,
  // plan-tsy-zone-v1 §1.4
  tsyEnterEventV1: TsyEnterEventV1,
  tsyExitEventV1: TsyExitEventV1,
  // plan-tsy-loot-v1 §4.4
  tsyCorpseSpawnEventV1: TsyCorpseSpawnEventV1,
  // plan-tsy-lifecycle-v1 §1.5 / §3.1 / §4
  tsyZoneActivatedV1: TsyZoneActivatedV1,
  tsyCollapseStartedV1: TsyCollapseStartedV1,
  tsyCollapseCompletedV1: TsyCollapseCompletedV1,
  daoxiangSpawnedV1: DaoxiangSpawnedV1,
  // plan-tsy-extract-v1 §4.1
  riftPortalStateV1: RiftPortalStateV1,
  riftPortalRemovedV1: RiftPortalRemovedV1,
  extractStartedV1: ExtractStartedV1,
  extractProgressV1: ExtractProgressV1,
  extractCompletedV1: ExtractCompletedV1,
  extractAbortedV1: ExtractAbortedV1,
  extractFailedV1: ExtractFailedV1,
  tsyCollapseStartedIpcV1: TsyCollapseStartedIpcV1,
  serverDataRiftPortalStateV1: ServerDataRiftPortalStateV1,
  serverDataRiftPortalRemovedV1: ServerDataRiftPortalRemovedV1,
  serverDataExtractStartedV1: ServerDataExtractStartedV1,
  serverDataExtractProgressV1: ServerDataExtractProgressV1,
  serverDataExtractCompletedV1: ServerDataExtractCompletedV1,
  serverDataExtractAbortedV1: ServerDataExtractAbortedV1,
  serverDataExtractFailedV1: ServerDataExtractFailedV1,
  serverDataTsyCollapseStartedIpcV1: ServerDataTsyCollapseStartedIpcV1,
  // plan-tsy-container-v1 §5.1 — TSY 容器搜刮
  containerStateV1: ContainerStateV1,
  searchStartedV1: SearchStartedV1,
  searchProgressV1: SearchProgressV1,
  searchCompletedV1: SearchCompletedV1,
  searchAbortedV1: SearchAbortedV1,
  clientRequestStartSearchV1: StartSearchRequestV1,
  clientRequestCancelSearchV1: CancelSearchRequestV1,
  // plan-tsy-hostile-v1 §6 — TSY 敌对 NPC 分层
  tsyHostileArchetypeV1: TsyHostileArchetypeV1,
  tsyNpcSpawnedV1: TsyNpcSpawnedV1,
  tsySentinelPhaseChangedV1: TsySentinelPhaseChangedV1,
  // ─── 炼器（武器）（plan-forge-v1 §4） ──────────
  forgeStep: ForgeStep,
  weaponTier: WeaponTier,
  temperBeat: TemperBeat,
  forgeOutcomeBucket: ForgeOutcomeBucket,
  forgeStepState: ForgeStepState,
  forgeBlueprintEntryV1: ForgeBlueprintEntryV1,
  weaponForgeStationDataV1: WeaponForgeStationDataV1,
  forgeSessionDataV1: ForgeSessionDataV1,
  forgeOutcomeDataV1: ForgeOutcomeDataV1,
  forgeBlueprintBookDataV1: ForgeBlueprintBookDataV1,
  forgeStartPayloadV1: ForgeStartPayloadV1,
  forgeOutcomePayloadV1: ForgeOutcomePayloadV1,
  serverDataForgeStationV1: ServerDataForgeStationV1,
  serverDataForgeSessionV1: ServerDataForgeSessionV1,
  serverDataForgeOutcomeV1: ServerDataForgeOutcomeV1,
  serverDataForgeBlueprintBookV1: ServerDataForgeBlueprintBookV1,
  clientRequestForgeStartSessionV1: ForgeStartSessionRequestV1,
  clientRequestForgeTemperingHitV1: ForgeTemperingHitRequestV1,
  clientRequestForgeInscriptionScrollV1: ForgeInscriptionScrollRequestV1,
  clientRequestForgeConsecrationInjectV1: ForgeConsecrationInjectRequestV1,
  clientRequestForgeStepAdvanceV1: ForgeStepAdvanceRequestV1,
  clientRequestForgeBlueprintTurnPageV1: ForgeBlueprintTurnPageRequestV1,
  clientRequestForgeLearnBlueprintV1: ForgeLearnBlueprintRequestV1,
  clientRequestForgeStationPlaceV1: ForgeStationPlaceRequestV1,
} as const satisfies Record<string, TSchema>;

export const GENERATED_SCHEMA_FILES = {
  "world-state-v1.json": SCHEMA_REGISTRY.worldStateV1,
  "agent-command-v1.json": SCHEMA_REGISTRY.agentCommandV1,
  "agent-world-model-envelope-v1.json": SCHEMA_REGISTRY.agentWorldModelEnvelopeV1,
  "agent-world-model-snapshot-v1.json": SCHEMA_REGISTRY.agentWorldModelSnapshotV1,
  "narration-v1.json": SCHEMA_REGISTRY.narrationV1,
  "npc-archetype-v1.json": SCHEMA_REGISTRY.npcArchetypeV1,
  "npc-spawn-source-v1.json": SCHEMA_REGISTRY.npcSpawnSourceV1,
  "npc-death-cause-v1.json": SCHEMA_REGISTRY.npcDeathCauseV1,
  "faction-id-v1.json": SCHEMA_REGISTRY.factionIdV1,
  "faction-event-kind-v1.json": SCHEMA_REGISTRY.factionEventKindV1,
  "npc-spawned-v1.json": SCHEMA_REGISTRY.npcSpawnedV1,
  "npc-death-v1.json": SCHEMA_REGISTRY.npcDeathV1,
  "poi-novice-kind-v1.json": SCHEMA_REGISTRY.poiNoviceKindV1,
  "poi-spawned-event-v1.json": SCHEMA_REGISTRY.poiSpawnedEventV1,
  "trespass-event-v1.json": SCHEMA_REGISTRY.trespassEventV1,
  "faction-event-v1.json": SCHEMA_REGISTRY.factionEventV1,
  "pseudo-vein-season-v1.json": SCHEMA_REGISTRY.pseudoVeinSeasonV1,
  "pseudo-vein-snapshot-v1.json": SCHEMA_REGISTRY.pseudoVeinSnapshotV1,
  "pseudo-vein-dissipate-event-v1.json":
    SCHEMA_REGISTRY.pseudoVeinDissipateEventV1,
  "zongmen-origin-id-v1.json": SCHEMA_REGISTRY.zongmenOriginIdV1,
  "zong-core-activation-v1.json": SCHEMA_REGISTRY.zongCoreActivationV1,
  "chat-message-v1.json": SCHEMA_REGISTRY.chatMessageV1,
  "chat-signal.json": SCHEMA_REGISTRY.chatSignal,
  "inventory-snapshot-v1.json": SCHEMA_REGISTRY.inventorySnapshotV1,
  "inventory-event-v1.json": SCHEMA_REGISTRY.inventoryEventV1,
  "server-data-v1.json": SCHEMA_REGISTRY.serverDataV1,
  "client-payload-v1.json": SCHEMA_REGISTRY.clientPayloadV1,
  "client-payload-welcome-v1.json": SCHEMA_REGISTRY.clientPayloadWelcomeV1,
  "client-payload-heartbeat-v1.json": SCHEMA_REGISTRY.clientPayloadHeartbeatV1,
  "client-payload-narration-v1.json": SCHEMA_REGISTRY.clientPayloadNarrationV1,
  "client-payload-zone-info-v1.json": SCHEMA_REGISTRY.clientPayloadZoneInfoV1,
  "client-payload-event-alert-v1.json": SCHEMA_REGISTRY.clientPayloadEventAlertV1,
  "client-payload-player-state-v1.json": SCHEMA_REGISTRY.clientPayloadPlayerStateV1,
  "insight-request-v1.json": SCHEMA_REGISTRY.insightRequestV1,
  "insight-offer-v1.json": SCHEMA_REGISTRY.insightOfferV1,
  "heart-demon-pregen-request-v1.json":
    SCHEMA_REGISTRY.heartDemonPregenRequestV1,
  "heart-demon-offer-draft-v1.json": SCHEMA_REGISTRY.heartDemonOfferDraftV1,
  "breakthrough-event-v1.json": SCHEMA_REGISTRY.breakthroughEventV1,
  "forge-event-v1.json": SCHEMA_REGISTRY.forgeEventV1,
  "biography-entry-v1.json": SCHEMA_REGISTRY.biographyEntryV1,
  "heart-demon-outcome-v1.json": SCHEMA_REGISTRY.heartDemonOutcomeV1,
  "cultivation-death-v1.json": SCHEMA_REGISTRY.cultivationDeathV1,
  "death-insight-request-v1.json": SCHEMA_REGISTRY.deathInsightRequestV1,
  "spirit-eye-migrate-v1.json": SCHEMA_REGISTRY.spiritEyeMigrateV1,
  "spirit-eye-discovered-v1.json": SCHEMA_REGISTRY.spiritEyeDiscoveredV1,
  "spirit-eye-used-for-breakthrough-v1.json":
    SCHEMA_REGISTRY.spiritEyeUsedForBreakthroughV1,
  "spirit-eye-coordinate-note-v1.json":
    SCHEMA_REGISTRY.spiritEyeCoordinateNoteV1,
  "death-registry-v1.json": SCHEMA_REGISTRY.deathRegistryV1,
  "deceased-index-entry-v1.json": SCHEMA_REGISTRY.deceasedIndexEntryV1,
  "deceased-snapshot-v1.json": SCHEMA_REGISTRY.deceasedSnapshotV1,
  "lifespan-event-v1.json": SCHEMA_REGISTRY.lifespanEventV1,
  "aging-event-v1.json": SCHEMA_REGISTRY.agingEventV1,
  "duo-she-event-v1.json": SCHEMA_REGISTRY.duoSheEventV1,
  "lifespan-cap-by-realm-v1.json": SCHEMA_REGISTRY.lifespanCapByRealmV1,
  "lifespan-component-v1.json": SCHEMA_REGISTRY.lifespanComponentV1,
  "lifespan-preview-v1.json": SCHEMA_REGISTRY.lifespanPreviewV1,
  "rebirth-chance-input-v1.json": SCHEMA_REGISTRY.rebirthChanceInputV1,
  "rebirth-chance-result-v1.json": SCHEMA_REGISTRY.rebirthChanceResultV1,
  "combat-realtime-event-v1.json": SCHEMA_REGISTRY.combatRealtimeEventV1,
  "combat-summary-v1.json": SCHEMA_REGISTRY.combatSummaryV1,
  "style-telemetry-color-snapshot-v1.json":
    SCHEMA_REGISTRY.styleTelemetryColorSnapshotV1,
  "style-balance-telemetry-event-v1.json":
    SCHEMA_REGISTRY.styleBalanceTelemetryEventV1,
  "violation-kind-v1.json": SCHEMA_REGISTRY.violationKindV1,
  "anticheat-report-v1.json": SCHEMA_REGISTRY.antiCheatReportV1,
  "armor-durability-changed-v1.json": SCHEMA_REGISTRY.armorDurabilityChangedV1,
  "tribulation-kind-v1.json": SCHEMA_REGISTRY.tribulationKindV1,
  "tribulation-phase-v1.json": SCHEMA_REGISTRY.tribulationPhaseV1,
  "du-xu-outcome-v1.json": SCHEMA_REGISTRY.duXuOutcomeV1,
  "du-xu-result-v1.json": SCHEMA_REGISTRY.duXuResultV1,
  "tribulation-event-v1.json": SCHEMA_REGISTRY.tribulationEventV1,
  "client-request-v1.json": SCHEMA_REGISTRY.clientRequestV1,
  "client-request-set-meridian-target-v1.json":
    SCHEMA_REGISTRY.clientRequestSetMeridianTargetV1,
  "client-request-breakthrough-v1.json": SCHEMA_REGISTRY.clientRequestBreakthroughV1,
  "client-request-start-du-xu-v1.json": SCHEMA_REGISTRY.clientRequestStartDuXuV1,
  "client-request-abort-tribulation-v1.json":
    SCHEMA_REGISTRY.clientRequestAbortTribulationV1,
  "client-request-heart-demon-decision-v1.json":
    SCHEMA_REGISTRY.clientRequestHeartDemonDecisionV1,
  "client-request-forge-v1.json": SCHEMA_REGISTRY.clientRequestForgeV1,
  "client-request-insight-decision-v1.json":
    SCHEMA_REGISTRY.clientRequestInsightDecisionV1,
  "client-request-duo-she-v1.json": SCHEMA_REGISTRY.clientRequestDuoSheV1,
  "client-request-qi-color-inspect-v1.json":
    SCHEMA_REGISTRY.clientRequestQiColorInspectV1,
  "client-request-equip-false-skin-v1.json":
    SCHEMA_REGISTRY.clientRequestEquipFalseSkinV1,
  "client-request-forge-false-skin-v1.json":
    SCHEMA_REGISTRY.clientRequestForgeFalseSkinV1,
  "client-request-use-life-core-v1.json":
    SCHEMA_REGISTRY.clientRequestUseLifeCoreV1,
  "client-request-mineral-probe-v1.json": SCHEMA_REGISTRY.clientRequestMineralProbeV1,
  "client-request-botany-harvest-v1.json":
    SCHEMA_REGISTRY.clientRequestBotanyHarvestV1,
  "client-request-combat-reincarnate-v1.json":
    SCHEMA_REGISTRY.clientRequestCombatReincarnateV1,
  "client-request-combat-terminate-v1.json":
    SCHEMA_REGISTRY.clientRequestCombatTerminateV1,
  "client-request-combat-create-new-character-v1.json":
    SCHEMA_REGISTRY.clientRequestCombatCreateNewCharacterV1,
  "client-request-use-quick-slot-v1.json":
    SCHEMA_REGISTRY.clientRequestUseQuickSlotV1,
  "client-request-quick-slot-bind-v1.json":
    SCHEMA_REGISTRY.clientRequestQuickSlotBindV1,
  "client-request-skill-bar-cast-v1.json":
    SCHEMA_REGISTRY.clientRequestSkillBarCastV1,
  "client-request-skill-bar-bind-v1.json":
    SCHEMA_REGISTRY.clientRequestSkillBarBindV1,
  "client-request-coffin-open-v1.json": SCHEMA_REGISTRY.clientRequestCoffinOpenV1,
  "client-request-trade-offer-v1.json": SCHEMA_REGISTRY.clientRequestTradeOfferV1,
  "client-request-trade-offer-response-v1.json":
    SCHEMA_REGISTRY.clientRequestTradeOfferResponseV1,
  "client-request-self-antidote-v1.json":
    SCHEMA_REGISTRY.clientRequestSelfAntidoteV1,
  "client-request-zhenfa-place-v1.json":
    SCHEMA_REGISTRY.clientRequestZhenfaPlaceV1,
  "client-request-zhenfa-trigger-v1.json":
    SCHEMA_REGISTRY.clientRequestZhenfaTriggerV1,
  "client-request-zhenfa-disarm-v1.json":
    SCHEMA_REGISTRY.clientRequestZhenfaDisarmV1,
  "client-request-start-extract-v1.json":
    SCHEMA_REGISTRY.clientRequestStartExtractV1,
  "client-request-cancel-extract-v1.json":
    SCHEMA_REGISTRY.clientRequestCancelExtractV1,
  "server-data-botany-harvest-progress-v1.json":
    SCHEMA_REGISTRY.serverDataBotanyHarvestProgressV1,
  "botany-model-overlay-v1.json": SCHEMA_REGISTRY.botanyModelOverlayV1,
  "botany-plant-v2-render-profile-v1.json":
    SCHEMA_REGISTRY.botanyPlantV2RenderProfileV1,
  "server-data-botany-plant-v2-render-profiles-v1.json":
    SCHEMA_REGISTRY.serverDataBotanyPlantV2RenderProfilesV1,
  "server-data-lumber-progress-v1.json":
    SCHEMA_REGISTRY.serverDataLumberProgressV1,
  "server-data-botany-skill-v1.json":
    SCHEMA_REGISTRY.serverDataBotanySkillV1,
  "server-data-death-screen-v1.json": SCHEMA_REGISTRY.serverDataDeathScreenV1,
  "server-data-terminate-screen-v1.json": SCHEMA_REGISTRY.serverDataTerminateScreenV1,
  "server-data-tribulation-state-v1.json":
    SCHEMA_REGISTRY.serverDataTribulationStateV1,
  "server-data-tribulation-broadcast-v1.json":
    SCHEMA_REGISTRY.serverDataTribulationBroadcastV1,
  "server-data-ascension-quota-v1.json": SCHEMA_REGISTRY.serverDataAscensionQuotaV1,
  "heart-demon-offer-choice-v1.json": SCHEMA_REGISTRY.heartDemonOfferChoiceV1,
  "server-data-heart-demon-offer-v1.json": SCHEMA_REGISTRY.serverDataHeartDemonOfferV1,
  "server-data-skill-xp-gain-v1.json":
    SCHEMA_REGISTRY.serverDataSkillXpGainV1,
  "server-data-skill-lv-up-v1.json":
    SCHEMA_REGISTRY.serverDataSkillLvUpV1,
  "server-data-skill-cap-changed-v1.json":
    SCHEMA_REGISTRY.serverDataSkillCapChangedV1,
  "server-data-skill-snapshot-v1.json":
    SCHEMA_REGISTRY.serverDataSkillSnapshotV1,
  "server-data-skill-scroll-used-v1.json":
    SCHEMA_REGISTRY.serverDataSkillScrollUsedV1,
  "burst-meridian-event-v1.json": SCHEMA_REGISTRY.burstMeridianEventV1,
  "qi-color-observed-v1.json": SCHEMA_REGISTRY.qiColorObservedV1,
  "skill-bar-entry-v1.json": SCHEMA_REGISTRY.skillBarEntryV1,
  "skill-bar-config-v1.json": SCHEMA_REGISTRY.skillBarConfigV1,
  "techniques-snapshot-v1.json": SCHEMA_REGISTRY.techniquesSnapshotV1,
  "server-data-skill-bar-config-v1.json":
    SCHEMA_REGISTRY.serverDataSkillBarConfigV1,
  "server-data-techniques-snapshot-v1.json":
    SCHEMA_REGISTRY.serverDataTechniquesSnapshotV1,
  "weapon-view-v1.json": SCHEMA_REGISTRY.weaponViewV1,
  "weapon-equipped-v1.json": SCHEMA_REGISTRY.weaponEquippedV1,
  "weapon-broken-v1.json": SCHEMA_REGISTRY.weaponBrokenV1,
  "treasure-view-v1.json": SCHEMA_REGISTRY.treasureViewV1,
  "treasure-equipped-v1.json": SCHEMA_REGISTRY.treasureEquippedV1,
  "server-data-weapon-equipped-v1.json":
    SCHEMA_REGISTRY.serverDataWeaponEquippedV1,
  "server-data-weapon-broken-v1.json":
    SCHEMA_REGISTRY.serverDataWeaponBrokenV1,
  "server-data-treasure-equipped-v1.json":
    SCHEMA_REGISTRY.serverDataTreasureEquippedV1,
  "dugu-poison-state-v1.json": SCHEMA_REGISTRY.duguPoisonStateV1,
  "dugu-poison-progress-event-v1.json":
    SCHEMA_REGISTRY.duguPoisonProgressEventV1,
  "dugu-obfuscation-state-v1.json": SCHEMA_REGISTRY.duguObfuscationStateV1,
  "dugu-antidote-result-v1.json": SCHEMA_REGISTRY.antidoteResultV1,
  "dugu-antidote-result-event-v1.json":
    SCHEMA_REGISTRY.antidoteResultEventV1,
  "dugu-revealed-event-v1.json": SCHEMA_REGISTRY.duguRevealedEventV1,
  "server-data-dugu-poison-state-v1.json":
    SCHEMA_REGISTRY.serverDataDuguPoisonStateV1,
  "false-skin-kind-v1.json": SCHEMA_REGISTRY.falseSkinKindV1,
  "false-skin-state-v1.json": SCHEMA_REGISTRY.falseSkinStateV1,
  "shed-event-v1.json": SCHEMA_REGISTRY.shedEventV1,
  "server-data-false-skin-state-v1.json":
    SCHEMA_REGISTRY.serverDataFalseSkinStateV1,
  "botany-ecology-snapshot-v1.json": SCHEMA_REGISTRY.botanyEcologySnapshotV1,
  "vfx-event-v1.json": SCHEMA_REGISTRY.vfxEventV1,
  // plan-social-v1 §7
  "exposure-kind-v1.json": SCHEMA_REGISTRY.exposureKindV1,
  "relationship-kind-v1.json": SCHEMA_REGISTRY.relationshipKindV1,
  "guardian-kind-v1.json": SCHEMA_REGISTRY.guardianKindV1,
  "renown-tag-v1.json": SCHEMA_REGISTRY.renownTagV1,
  "relationship-snapshot-v1.json": SCHEMA_REGISTRY.relationshipSnapshotV1,
  "renown-snapshot-v1.json": SCHEMA_REGISTRY.renownSnapshotV1,
  "faction-membership-snapshot-v1.json":
    SCHEMA_REGISTRY.factionMembershipSnapshotV1,
  "player-social-snapshot-v1.json": SCHEMA_REGISTRY.playerSocialSnapshotV1,
  "deceased-renown-snapshot-v1.json":
    SCHEMA_REGISTRY.deceasedRenownSnapshotV1,
  "deceased-exposure-snapshot-v1.json":
    SCHEMA_REGISTRY.deceasedExposureSnapshotV1,
  "deceased-social-snapshot-v1.json":
    SCHEMA_REGISTRY.deceasedSocialSnapshotV1,
  "social-remote-identity-v1.json": SCHEMA_REGISTRY.socialRemoteIdentityV1,
  "social-anonymity-payload-v1.json": SCHEMA_REGISTRY.socialAnonymityPayloadV1,
  "social-exposure-event-v1.json": SCHEMA_REGISTRY.socialExposureEventV1,
  "social-pact-event-v1.json": SCHEMA_REGISTRY.socialPactEventV1,
  "social-feud-event-v1.json": SCHEMA_REGISTRY.socialFeudEventV1,
  "social-renown-delta-v1.json": SCHEMA_REGISTRY.socialRenownDeltaV1,
  "spirit-niche-activate-guardian-v1.json":
    SCHEMA_REGISTRY.spiritNicheActivateGuardianV1,
  "niche-intrusion-event-v1.json": SCHEMA_REGISTRY.nicheIntrusionEventV1,
  "niche-guardian-fatigue-v1.json": SCHEMA_REGISTRY.nicheGuardianFatigueV1,
  "niche-guardian-broken-v1.json": SCHEMA_REGISTRY.nicheGuardianBrokenV1,
  "sparring-invite-payload-v1.json": SCHEMA_REGISTRY.sparringInvitePayloadV1,
  "trade-item-summary-v1.json": SCHEMA_REGISTRY.tradeItemSummaryV1,
  "trade-offer-payload-v1.json": SCHEMA_REGISTRY.tradeOfferPayloadV1,
  "server-data-social-anonymity-v1.json":
    SCHEMA_REGISTRY.serverDataSocialAnonymityV1,
  "server-data-social-exposure-v1.json":
    SCHEMA_REGISTRY.serverDataSocialExposureV1,
  "server-data-social-pact-v1.json": SCHEMA_REGISTRY.serverDataSocialPactV1,
  "server-data-social-feud-v1.json": SCHEMA_REGISTRY.serverDataSocialFeudV1,
  "server-data-social-renown-delta-v1.json":
    SCHEMA_REGISTRY.serverDataSocialRenownDeltaV1,
  "server-data-niche-intrusion-v1.json":
    SCHEMA_REGISTRY.serverDataNicheIntrusionV1,
  "server-data-niche-guardian-fatigue-v1.json":
    SCHEMA_REGISTRY.serverDataNicheGuardianFatigueV1,
  "server-data-niche-guardian-broken-v1.json":
    SCHEMA_REGISTRY.serverDataNicheGuardianBrokenV1,
  "server-data-sparring-invite-v1.json":
    SCHEMA_REGISTRY.serverDataSparringInviteV1,
  "server-data-trade-offer-v1.json": SCHEMA_REGISTRY.serverDataTradeOfferV1,
  "fog-shape-v1.json": SCHEMA_REGISTRY.fogShapeV1,
  "realm-vision-params-v1.json": SCHEMA_REGISTRY.realmVisionParamsV1,
  "server-data-realm-vision-params-v1.json":
    SCHEMA_REGISTRY.serverDataRealmVisionParamsV1,
  "sense-kind-v1.json": SCHEMA_REGISTRY.senseKindV1,
  "sense-entry-v1.json": SCHEMA_REGISTRY.senseEntryV1,
  "spiritual-sense-targets-v1.json": SCHEMA_REGISTRY.spiritualSenseTargetsV1,
  "server-data-spiritual-sense-targets-v1.json":
    SCHEMA_REGISTRY.serverDataSpiritualSenseTargetsV1,
  "tutorial-hook-v1.json": SCHEMA_REGISTRY.tutorialHookV1,
  "tutorial-hook-event-v1.json": SCHEMA_REGISTRY.tutorialHookEventV1,
  "coffin-opened-v1.json": SCHEMA_REGISTRY.coffinOpenedV1,
  "client-request-sparring-invite-response-v1.json":
    SCHEMA_REGISTRY.clientRequestSparringInviteResponseV1,
  "audio-event-v1.json": SCHEMA_REGISTRY.audioEventV1,
  "play-sound-recipe-event-v1.json": SCHEMA_REGISTRY.playSoundRecipeEventV1,
  "stop-sound-recipe-event-v1.json": SCHEMA_REGISTRY.stopSoundRecipeEventV1,
  "sound-recipe-v1.json": SCHEMA_REGISTRY.soundRecipeV1,
  // 炼丹 (plan-alchemy-v1 §4)
  "alchemy-outcome-bucket.json": SCHEMA_REGISTRY.alchemyOutcomeBucket,
  "alchemy-intervention-v1.json": SCHEMA_REGISTRY.alchemyInterventionV1,
  "alchemy-recipe-entry-v1.json": SCHEMA_REGISTRY.alchemyRecipeEntryV1,
  "alchemy-stage-hint-v1.json": SCHEMA_REGISTRY.alchemyStageHintV1,
  "alchemy-contamination-level-v1.json":
    SCHEMA_REGISTRY.alchemyContaminationLevelV1,
  "alchemy-session-start-v1.json": SCHEMA_REGISTRY.alchemySessionStartV1,
  "alchemy-session-end-v1.json": SCHEMA_REGISTRY.alchemySessionEndV1,
  "alchemy-intervention-result-v1.json":
    SCHEMA_REGISTRY.alchemyInterventionResultV1,
  "alchemy-insight-v1.json": SCHEMA_REGISTRY.alchemyInsightV1,
  "server-data-alchemy-furnace-v1.json":
    SCHEMA_REGISTRY.serverDataAlchemyFurnaceV1,
  "server-data-alchemy-session-v1.json":
    SCHEMA_REGISTRY.serverDataAlchemySessionV1,
  "server-data-alchemy-outcome-forecast-v1.json":
    SCHEMA_REGISTRY.serverDataAlchemyOutcomeForecastV1,
  "server-data-alchemy-outcome-resolved-v1.json":
    SCHEMA_REGISTRY.serverDataAlchemyOutcomeResolvedV1,
  "server-data-alchemy-recipe-book-v1.json":
    SCHEMA_REGISTRY.serverDataAlchemyRecipeBookV1,
  "server-data-alchemy-contamination-v1.json":
    SCHEMA_REGISTRY.serverDataAlchemyContaminationV1,
  "client-request-alchemy-open-furnace-v1.json":
    SCHEMA_REGISTRY.clientRequestAlchemyOpenFurnaceV1,
  "client-request-alchemy-feed-slot-v1.json":
    SCHEMA_REGISTRY.clientRequestAlchemyFeedSlotV1,
  "client-request-alchemy-take-back-v1.json":
    SCHEMA_REGISTRY.clientRequestAlchemyTakeBackV1,
  "client-request-alchemy-ignite-v1.json":
    SCHEMA_REGISTRY.clientRequestAlchemyIgniteV1,
  "client-request-alchemy-intervention-v1.json":
    SCHEMA_REGISTRY.clientRequestAlchemyInterventionV1,
  "client-request-alchemy-turn-page-v1.json":
    SCHEMA_REGISTRY.clientRequestAlchemyTurnPageV1,
  "client-request-alchemy-learn-recipe-v1.json":
    SCHEMA_REGISTRY.clientRequestAlchemyLearnRecipeV1,
  "client-request-alchemy-take-pill-v1.json":
    SCHEMA_REGISTRY.clientRequestAlchemyTakePillV1,
  // plan-tsy-zone-v1 §1.4 — JSON Schema 导出供 Rust serde 双端校验
  "tsy-enter-event-v1.json": SCHEMA_REGISTRY.tsyEnterEventV1,
  "tsy-exit-event-v1.json": SCHEMA_REGISTRY.tsyExitEventV1,
  // plan-tsy-loot-v1 §4.4
  "tsy-corpse-spawn-event-v1.json": SCHEMA_REGISTRY.tsyCorpseSpawnEventV1,
  // plan-tsy-lifecycle-v1 §1.5 / §3.1 / §4
  "tsy-zone-activated-v1.json": SCHEMA_REGISTRY.tsyZoneActivatedV1,
  "tsy-collapse-started-v1.json": SCHEMA_REGISTRY.tsyCollapseStartedV1,
  "tsy-collapse-completed-v1.json": SCHEMA_REGISTRY.tsyCollapseCompletedV1,
  "daoxiang-spawned-v1.json": SCHEMA_REGISTRY.daoxiangSpawnedV1,
  // plan-tsy-extract-v1 §4.1
  "rift-portal-state-v1.json": SCHEMA_REGISTRY.riftPortalStateV1,
  "rift-portal-removed-v1.json": SCHEMA_REGISTRY.riftPortalRemovedV1,
  "extract-started-v1.json": SCHEMA_REGISTRY.extractStartedV1,
  "extract-progress-v1.json": SCHEMA_REGISTRY.extractProgressV1,
  "extract-completed-v1.json": SCHEMA_REGISTRY.extractCompletedV1,
  "extract-aborted-v1.json": SCHEMA_REGISTRY.extractAbortedV1,
  "extract-failed-v1.json": SCHEMA_REGISTRY.extractFailedV1,
  "tsy-collapse-started-ipc-v1.json": SCHEMA_REGISTRY.tsyCollapseStartedIpcV1,
  "server-data-rift-portal-state-v1.json":
    SCHEMA_REGISTRY.serverDataRiftPortalStateV1,
  "server-data-rift-portal-removed-v1.json":
    SCHEMA_REGISTRY.serverDataRiftPortalRemovedV1,
  "server-data-extract-started-v1.json":
    SCHEMA_REGISTRY.serverDataExtractStartedV1,
  "server-data-extract-progress-v1.json":
    SCHEMA_REGISTRY.serverDataExtractProgressV1,
  "server-data-extract-completed-v1.json":
    SCHEMA_REGISTRY.serverDataExtractCompletedV1,
  "server-data-extract-aborted-v1.json":
    SCHEMA_REGISTRY.serverDataExtractAbortedV1,
  "server-data-extract-failed-v1.json":
    SCHEMA_REGISTRY.serverDataExtractFailedV1,
  "server-data-tsy-collapse-started-ipc-v1.json":
    SCHEMA_REGISTRY.serverDataTsyCollapseStartedIpcV1,
  // plan-tsy-container-v1 §5.1
  "container-state-v1.json": SCHEMA_REGISTRY.containerStateV1,
  "search-started-v1.json": SCHEMA_REGISTRY.searchStartedV1,
  "search-progress-v1.json": SCHEMA_REGISTRY.searchProgressV1,
  "search-completed-v1.json": SCHEMA_REGISTRY.searchCompletedV1,
  "search-aborted-v1.json": SCHEMA_REGISTRY.searchAbortedV1,
  "client-request-start-search-v1.json": SCHEMA_REGISTRY.clientRequestStartSearchV1,
  "client-request-cancel-search-v1.json": SCHEMA_REGISTRY.clientRequestCancelSearchV1,
  // plan-tsy-hostile-v1 §6
  "tsy-hostile-archetype-v1.json": SCHEMA_REGISTRY.tsyHostileArchetypeV1,
  "tsy-npc-spawned-v1.json": SCHEMA_REGISTRY.tsyNpcSpawnedV1,
  "tsy-sentinel-phase-changed-v1.json": SCHEMA_REGISTRY.tsySentinelPhaseChangedV1,
  // ─── 炼器（武器）（plan-forge-v1 §4） ──────────
  "forge-step.json": SCHEMA_REGISTRY.forgeStep,
  "weapon-tier.json": SCHEMA_REGISTRY.weaponTier,
  "temper-beat.json": SCHEMA_REGISTRY.temperBeat,
  "forge-outcome-bucket.json": SCHEMA_REGISTRY.forgeOutcomeBucket,
  "forge-step-state.json": SCHEMA_REGISTRY.forgeStepState,
  "forge-blueprint-entry-v1.json": SCHEMA_REGISTRY.forgeBlueprintEntryV1,
  "weapon-forge-station-data-v1.json": SCHEMA_REGISTRY.weaponForgeStationDataV1,
  "forge-session-data-v1.json": SCHEMA_REGISTRY.forgeSessionDataV1,
  "forge-outcome-data-v1.json": SCHEMA_REGISTRY.forgeOutcomeDataV1,
  "forge-blueprint-book-data-v1.json": SCHEMA_REGISTRY.forgeBlueprintBookDataV1,
  "forge-start-payload-v1.json": SCHEMA_REGISTRY.forgeStartPayloadV1,
  "forge-outcome-payload-v1.json": SCHEMA_REGISTRY.forgeOutcomePayloadV1,
  "server-data-forge-station-v1.json": SCHEMA_REGISTRY.serverDataForgeStationV1,
  "server-data-forge-session-v1.json": SCHEMA_REGISTRY.serverDataForgeSessionV1,
  "server-data-forge-outcome-v1.json": SCHEMA_REGISTRY.serverDataForgeOutcomeV1,
  "server-data-forge-blueprint-book-v1.json": SCHEMA_REGISTRY.serverDataForgeBlueprintBookV1,
  "client-request-forge-start-session-v1.json": SCHEMA_REGISTRY.clientRequestForgeStartSessionV1,
  "client-request-forge-tempering-hit-v1.json": SCHEMA_REGISTRY.clientRequestForgeTemperingHitV1,
  "client-request-forge-inscription-scroll-v1.json": SCHEMA_REGISTRY.clientRequestForgeInscriptionScrollV1,
  "client-request-forge-consecration-inject-v1.json": SCHEMA_REGISTRY.clientRequestForgeConsecrationInjectV1,
  "client-request-forge-step-advance-v1.json": SCHEMA_REGISTRY.clientRequestForgeStepAdvanceV1,
  "client-request-forge-blueprint-turn-page-v1.json": SCHEMA_REGISTRY.clientRequestForgeBlueprintTurnPageV1,
  "client-request-forge-learn-blueprint-v1.json": SCHEMA_REGISTRY.clientRequestForgeLearnBlueprintV1,
  "client-request-forge-station-place-v1.json": SCHEMA_REGISTRY.clientRequestForgeStationPlaceV1,
} as const satisfies Record<string, TSchema>;

export type SchemaRegistryKey = keyof typeof SCHEMA_REGISTRY;
export type GeneratedSchemaFileName = keyof typeof GENERATED_SCHEMA_FILES;
