package com.bong.client.hud;

public enum HudRenderLayer {
    BASELINE,
    ZONE,
    MINI_BODY,
    QUICK_BAR,
    CAST_BAR,
    EVENT_STREAM,
    JIEMAI_RING,
    SPELL_VOLUME,
    CARRIER,
    YIDAO,
    BOTANY,
    DERIVED_ATTR,
    TOAST,
    VISUAL,
    SPIRITUAL_SENSE,
    EDGE_FEEDBACK,
    STATUS_EFFECTS,
    STAMINA_BAR,
    SEARCH_PROGRESS,
    DAMAGE_FLOATER,
    FLIGHT_HUD,
    TRIBULATION,
    NEAR_DEATH,
    TSY_EXTRACT,
    REALM_COLLAPSE
}
