package com.bong.client.hud;

public enum HudRenderLayer {
    BASELINE,
    ZONE,
    COMPASS,
    QI_RADAR,
    THREAT_INDICATOR,
    HUD_VARIANT,
    TARGET_INFO,
    MINI_BODY,
    QUICK_BAR,
    CAST_BAR,
    EVENT_STREAM,
    JIEMAI_RING,
    SPELL_VOLUME,
    CARRIER,
    YIDAO,
    BOTANY,
    GATHERING,
    DERIVED_ATTR,
    TOAST,
    VISUAL,
    SPIRITUAL_SENSE,
    EDGE_FEEDBACK,
    STATUS_EFFECTS,
    PROCESSING_HUD,
    LINGTIAN_OVERLAY,
    STAMINA_BAR,
    MOVEMENT_HUD,
    SEARCH_PROGRESS,
    DAMAGE_FLOATER,
    FLIGHT_HUD,
    COFFIN,
    TRIBULATION,
    NEAR_DEATH,
    TSY_EXTRACT,
    REALM_COLLAPSE,
    MERIDIAN_OPEN,
    CONNECTION_STATUS,
    VORTEX_CHARGE,
    VORTEX_COOLDOWN,
    VORTEX_BACKFIRE,
    VORTEX_TURBULENCE,
    DUGU_TAINT_WARNING,
    DUGU_TAINT_INDICATOR,
    DUGU_REVEAL_RISK,
    DUGU_SELF_CURE_PROGRESS,
    DUGU_SHROUD,
    /** plan-combat-skill-feedback-bridges-v1 P5：永久真元上限衰减 HUD 闪烁条。§视听精度文档待人工补 */
    DUGU_QI_DECAY,
    POISON_TRAIT,
    DANDAO_MUTATION,
    SWORD_BOND,
    /** plan-offscreen-war-v1 P9：战事双色血条 + WarPhase 文字。 */
    FACTION_WAR,
    /** plan-fauna-stitched-beast-v1 P3：兽核吸收幻觉层（绿边像差/bar偏移/视野旋转）。 */
    HALLUCINATION,
    /** plan-dying-elder-v1 P3：垂死大能遭遇 HUD（真元进度条 + 三按钮 + 背叛概率）。 */
    DYING_ELDER,
    /** plan-agent-ui-data-v1 P3：天道动态面板 VFX overlay（粒子底噪、vignette、shake）。 */
    AGENT_UI
}
