"""worldgen-v4 P0 行为等价对拍 — v3 carved-surface baseline pin.

This test locks the frozen v3 surface contract captured in
``worldgen/fixtures/v3_surface_baseline.json``.  The golden is the REAL v3
walkable surface (rift→fracture→neg→entrance sculpting, then clamps), NOT
``round(height)``.  Three guarantees:

1. Re-running the v3 generators + carve math today still yields the exact
   baseline numbers (catches accidental landscape drift across every
   representative profile before the span refactor changes anything).
2. (after P0 shim lands) the spans folded from those same 2D outputs reproduce
   the baseline surface — see ``test_spans_shim.py``.
3. ANTI-CIRCULARITY: hand-computed literal anchors (``HandCalcedV3CarveAnchors``)
   pin specific (height, mask…) inputs to a v3 ``top_y`` value worked out by hand
   from column.rs, covering rift / fracture / neg_pressure / entrance.  If the
   carve formula in ``v3_surface_top_y`` is misread, these literals撞红 even
   though the golden was generated by the same function — the golden can no
   longer silently agree with itself.

If a profile legitimately changes its landscape, regenerate the golden with
``python3 tests/regenerate_v3_baseline.py`` and review the diff — never edit the
JSON by hand to silence this test.
"""

from __future__ import annotations

import json
import unittest
from pathlib import Path

import numpy as np

from regenerate_v3_baseline import v3_carved_surface
from scripts.terrain_gen.spans_shim import v3_surface_top_y
from v3_baseline_zones import TILE_SIZE, build_baseline_buffer

REPO_ROOT = Path(__file__).resolve().parents[2]
BASELINE_PATH = REPO_ROOT / "worldgen/fixtures/v3_surface_baseline.json"


def _col_index(local_x: int, local_z: int) -> int:
    return local_z * TILE_SIZE + local_x


class HandCalcedV3CarveAnchors(unittest.TestCase):
    """Literal anchors worked out by hand from column.rs::resolve_column.

    Each case fixes the carve inputs and the expected ``top_y`` so the formula
    is pinned against an INDEPENDENT hand calculation, breaking the golden's
    "same code generates and checks" circularity.  bedrock_y = -64; the initial
    clamp_world_y ceiling is 429, the final clamp range is [-62, 430].
    """

    def test_rift_only_anchor(self) -> None:
        # height 80 → round 80. rift_axis_sdf=0.5 (<0.9), rim_edge_mask=0.25.
        # ① carve = round((1-0.5)*22 + 0.25*4) = round(11.0 + 1.0) = round(12.0) = 12.
        # → top_y = 80 - 12 = 68. No fracture/neg/entrance.
        got = v3_surface_top_y(
            height=80.0,
            rift_axis_sdf=0.5,
            rim_edge_mask=0.25,
            fracture_mask=0.0,
            neg_pressure=0.0,
            entrance_mask=0.0,
        )
        self.assertEqual(
            got,
            68,
            "rift sculpt: round((1-0.5)*22 + 0.25*4)=12 carved off 80 → 68; "
            f"got {got}. A wrong rift coefficient would miss this literal.",
        )

    def test_fracture_only_anchor(self) -> None:
        # height 100 → round 100. fracture_mask=0.90 (>0.7), int truncation IN
        # f32: (0.90f32 - 0.7f32) * 300 = 59.999… → as i32 = 59 (NOT the f64 value
        # 60.000… → 60).  ② crack = 59 → top_y = max(-58, 41) = 41.
        got = v3_surface_top_y(
            height=100.0,
            rift_axis_sdf=99.0,
            rim_edge_mask=0.0,
            fracture_mask=0.90,
            neg_pressure=0.0,
            entrance_mask=0.0,
        )
        self.assertEqual(
            got,
            41,
            "fracture crack: f32 (0.90-0.7)*300 = 59.99… truncates to 59 off "
            f"100 → 41; got {got}. Doing it in f64 would give 60 → 40 — a real "
            "off-by-1 vs the v3 Rust f32 path.",
        )

    def test_fracture_truncation_distinguishes_from_round(self) -> None:
        # height 100. fracture_mask=0.701 → (0.701-0.7)*300 = 0.3.
        # Rust `as i32` truncates 0.3 → 0; round() would also give 0 here, so use
        # a value whose fraction crosses 0.5 to distinguish: fracture_mask=0.702
        # → (0.002)*300 = 0.6 → int() = 0 but round() = 1. v3 must give 0.
        got = v3_surface_top_y(
            height=100.0,
            rift_axis_sdf=99.0,
            rim_edge_mask=0.0,
            fracture_mask=0.702,
            neg_pressure=0.0,
            entrance_mask=0.0,
        )
        self.assertEqual(
            got,
            100,
            "fracture crack int((0.702-0.7)*300)=int(0.6)=0 (truncate); round() "
            f"would carve 1 → 99. v3 truncates, so surface stays 100; got {got}.",
        )

    def test_neg_pressure_only_anchor(self) -> None:
        # height 90 → round 90. neg_pressure=0.5 (>0.18):
        # ③ sink = round(0.5*14) = round(7.0) = 7 → top_y = 90 - 7 = 83.
        got = v3_surface_top_y(
            height=90.0,
            rift_axis_sdf=99.0,
            rim_edge_mask=0.0,
            fracture_mask=0.0,
            neg_pressure=0.5,
            entrance_mask=0.0,
        )
        self.assertEqual(
            got,
            83,
            f"neg_pressure sink: round(0.5*14)=7 off 90 → 83; got {got}",
        )

    def test_entrance_only_anchor(self) -> None:
        # height 72 → round 72. entrance_mask=0.45 (>0.16):
        # ④ sink = round(0.45*10) = round(4.5) = 5 (half AWAY from zero, like Rust
        #    f32::round; banker's round would give 4). → top_y = 72 - 5 = 67.
        got = v3_surface_top_y(
            height=72.0,
            rift_axis_sdf=99.0,
            rim_edge_mask=0.0,
            fracture_mask=0.0,
            neg_pressure=0.0,
            entrance_mask=0.45,
        )
        self.assertEqual(
            got,
            67,
            "entrance sink: round(0.45*10)=round(4.5)=5 (HALF AWAY, not banker's "
            f"4) off 72 → 67; got {got}. Banker's rounding would give 68.",
        )

    def test_combined_all_four_carves_anchor(self) -> None:
        # height 95 → round 95.
        # ① rift  sdf=0.6: round((0.4)*22 + 0) = round(8.8) = 9 → 86
        # ② frac  0.80:    int((0.10)*300) = int(30.0) = 30 → max(-58, 56) = 56
        # ③ neg   0.30:    round(0.30*14) = round(4.2) = 4 → 52
        # ④ ent   0.20:    round(0.20*10) = round(2.0) = 2 → 50
        got = v3_surface_top_y(
            height=95.0,
            rift_axis_sdf=0.6,
            rim_edge_mask=0.0,
            fracture_mask=0.80,
            neg_pressure=0.30,
            entrance_mask=0.20,
        )
        self.assertEqual(
            got,
            50,
            "stacked carves 95 →(rift 9)86 →(frac 30)56 →(neg 4)52 →(ent 2)50; "
            f"got {got}. Any single mis-ordered/mis-rounded step breaks this.",
        )

    def test_initial_height_clamp_anchor(self) -> None:
        # height 999 → clamp_world_y caps at MIN_Y + WORLD_HEIGHT - 3 = 429 before
        # any carve; no carves here → final clamp keeps 429.
        got = v3_surface_top_y(999.0, 99.0, 0.0, 0.0, 0.0, 0.0)
        self.assertEqual(
            got,
            429,
            f"height above the world ceiling clamps to 429 (clamp_world_y); got {got}",
        )

    def test_fracture_floor_clamp_anchor(self) -> None:
        # height 30, fracture_mask=1.0 → crack = int(f32(0.3)*300)=90 → top_y =
        # max(bedrock_y+6, 30-90) = max(-58, -60) = -58. The fracture floor pins
        # the deepest carve to bedrock_y+6 = -58 (a shallower base, e.g. 80, would
        # only reach -10 and never touch the floor).
        got = v3_surface_top_y(30.0, 99.0, 0.0, 1.0, 0.0, 0.0)
        self.assertEqual(
            got,
            -58,
            "saturated fracture floors at bedrock_y+6 = -58 (30-90=-60 clamped); "
            f"got {got}",
        )


class V3SurfaceBaselineTest(unittest.TestCase):
    def setUp(self) -> None:
        self.baseline = json.loads(BASELINE_PATH.read_text(encoding="utf-8"))
        self.assertGreater(len(self.baseline), 0, "baseline fixture is empty")

    def test_baseline_covers_all_representative_shapes(self) -> None:
        profiles = {row["profile"] for row in self.baseline}
        self.assertEqual(
            profiles,
            {"normal", "water", "sky_isle", "cave", "abyssal", "rift", "waste"},
            "baseline must cover every column shape AND every carve branch "
            f"(rift/fracture/neg/entrance); got {sorted(profiles)}",
        )

    def test_baseline_actually_exercises_each_carve_branch(self) -> None:
        # The whole point of widening the matrix: every carve type must produce
        # at least one column whose v3 surface differs from round(height). If a
        # branch never fires, the golden is back to a no-op self-pin.
        carved_below_raw = 0
        for profile_key in ("rift", "waste", "cave", "abyssal"):
            buffer = build_baseline_buffer(profile_key)
            height = np.asarray(buffer.layers["height"])
            rows = [r for r in self.baseline if r["profile"] == profile_key]
            for row in rows:
                idx = _col_index(row["local_x"], row["local_z"])
                raw = round(float(height[idx]))
                if row["surface_y"] < raw:
                    carved_below_raw += 1
        self.assertGreater(
            carved_below_raw,
            0,
            "no carve branch dropped any column below round(height); the golden "
            "is not exercising the rift/fracture/neg/entrance sculpt at all",
        )
        # And specifically the deepest carve (rift+fracture) must reach bedrock+6.
        rift_axis = next(
            r for r in self.baseline
            if r["profile"] == "rift" and (r["local_x"], r["local_z"]) == (100, 100)
        )
        self.assertEqual(
            rift_axis["surface_y"],
            -58,
            "rift axis center should carve to bedrock_y+6 = -58 (fracture_mask=1.0); "
            f"got {rift_axis['surface_y']} — the fracture branch is not firing",
        )

    def test_baseline_includes_real_water_columns(self) -> None:
        water_rows = [
            row
            for row in self.baseline
            if row["profile"] == "water" and row["water_y"] is not None
        ]
        self.assertGreater(
            len(water_rows),
            0,
            "water profile baseline must contain at least one flooded column so "
            "the shim's water_y equivalence is actually exercised",
        )

    def test_v3_generators_still_match_frozen_baseline(self) -> None:
        # Group rows by profile so each generator only runs once.
        rows_by_profile: dict[str, list[dict]] = {}
        for row in self.baseline:
            rows_by_profile.setdefault(row["profile"], []).append(row)

        for profile_key, rows in rows_by_profile.items():
            buffer = build_baseline_buffer(profile_key)
            water = np.asarray(buffer.layers["water_level"])
            biome = np.asarray(buffer.layers["biome_id"])
            for row in rows:
                idx = _col_index(row["local_x"], row["local_z"])
                got_surface = v3_carved_surface(buffer, idx)
                water_level = float(water[idx])
                got_water = (
                    round(water_level) if water_level >= 0.0 else None
                )
                got_biome = int(biome[idx])
                col = (row["local_x"], row["local_z"])
                self.assertEqual(
                    got_surface,
                    row["surface_y"],
                    f"{profile_key}{col}: v3 carved surface drifted from baseline "
                    f"(expected {row['surface_y']}, got {got_surface}); if the "
                    f"profile changed on purpose regenerate the golden",
                )
                self.assertEqual(
                    got_water,
                    row["water_y"],
                    f"{profile_key}{col}: water_y drifted from v3 baseline "
                    f"(expected {row['water_y']}, got {got_water})",
                )
                self.assertEqual(
                    got_biome,
                    row["biome_id"],
                    f"{profile_key}{col}: biome_id drifted from v3 baseline "
                    f"(expected {row['biome_id']}, got {got_biome})",
                )


if __name__ == "__main__":
    unittest.main()
