facing = "+z"
mirror_x = 0.0
size = 500

[materials]
flesh_main = [138, 42, 42]
flesh_dark = [90, 26, 26]
bone_main = [216, 204, 176]
bone_dark = [184, 168, 136]
tendon_tube = [217, 160, 140]
tendon_highlight = [232, 188, 168]
tendon_fiber = [192, 120, 104]

[features]
flesh_ribs = { elements = ["empty_rib", "half_rib", "full_rib", "empty_bot_rib", "half_bot_rib", "full_bot_rib", "empty_top_rib", "half_top_rib", "full_top_rib"], must_show_in = ["FRONT", "SIDE_R", "SIDE_L", "3/4", "TOP"], min_px = 1 }
bone_caps = { elements = ["empty_bone_cap", "half_bone_cap", "full_bone_cap"], must_show_in = ["FRONT", "SIDE_R", "SIDE_L", "3/4", "TOP"], min_px = 1 }
tendon_sac = { elements = ["empty_sac_", "half_sac_", "full_sac_"], must_show_in = ["FRONT", "SIDE_R", "SIDE_L", "3/4"], min_px = 1 }
top_neck = { elements = ["empty_neck", "half_neck", "full_neck"], must_show_in = ["FRONT", "SIDE_R", "SIDE_L", "3/4", "TOP"], min_px = 1 }
