//! Frozen P2 oracle derived from the pre-datafication `blocks.rs` match.
//!
//! It is intentionally test-only: production uses the catalog and `BlockKind::from_str`; this preserves the exact 213-key baseline (211 direct names plus two aliases).

use valence::prelude::BlockState;

pub(crate) const LEGACY_BLOCK_ORACLE: &[(&str, &str)] = &[
    ("stone", "stone"),
    ("smooth_stone", "smooth_stone"),
    ("coarse_dirt", "coarse_dirt"),
    ("gravel", "gravel"),
    ("grass_block", "grass_block"),
    ("dirt", "dirt"),
    ("sand", "sand"),
    ("sandstone", "sandstone"),
    ("red_sandstone", "red_sandstone"),
    ("red_sand", "red_sand"),
    ("chiseled_red_sandstone", "chiseled_red_sandstone"),
    ("terracotta", "terracotta"),
    ("red_terracotta", "red_terracotta"),
    ("blackstone", "blackstone"),
    ("basalt", "basalt"),
    ("polished_basalt", "polished_basalt"),
    ("magma_block", "magma_block"),
    ("crimson_nylium", "crimson_nylium"),
    ("calcite", "calcite"),
    ("snow_block", "snow_block"),
    ("packed_ice", "packed_ice"),
    ("blue_ice", "blue_ice"),
    ("podzol", "podzol"),
    ("rooted_dirt", "rooted_dirt"),
    ("soul_sand", "soul_sand"),
    ("soul_soil", "soul_soil"),
    ("bone_block", "bone_block"),
    ("mud", "mud"),
    ("clay", "clay"),
    ("moss_block", "moss_block"),
    ("moss_carpet", "moss_carpet"),
    ("andesite", "andesite"),
    ("polished_andesite", "polished_andesite"),
    ("polished_diorite", "polished_diorite"),
    ("deepslate", "deepslate"),
    ("cobbled_deepslate", "cobbled_deepslate"),
    ("tuff", "tuff"),
    ("cobblestone", "cobblestone"),
    ("mossy_cobblestone", "mossy_cobblestone"),
    ("dead_bush", "dead_bush"),
    ("grass", "grass"),
    ("cobweb", "cobweb"),
    ("gray_concrete_powder", "gray_concrete_powder"),
    ("cobblestone_wall", "cobblestone_wall"),
    ("torch", "torch"),
    ("stone_button", "stone_button"),
    ("muddy_mangrove_roots", "muddy_mangrove_roots"),
    ("oak_log", "oak_log"),
    ("stripped_oak_log", "stripped_oak_log"),
    ("oak_leaves", "oak_leaves"),
    ("birch_log", "birch_log"),
    ("birch_leaves", "birch_leaves"),
    ("stripped_birch_log", "stripped_birch_log"),
    ("spruce_log", "spruce_log"),
    ("spruce_leaves", "spruce_leaves"),
    ("stripped_spruce_log", "stripped_spruce_log"),
    ("jungle_log", "jungle_log"),
    ("azalea_leaves", "azalea_leaves"),
    ("flowering_azalea_leaves", "flowering_azalea_leaves"),
    ("mangrove_log", "mangrove_log"),
    ("mangrove_leaves", "mangrove_leaves"),
    ("mangrove_roots", "mangrove_roots"),
    ("bamboo_block", "bamboo_block"),
    ("stripped_bamboo_block", "stripped_bamboo_block"),
    ("crimson_stem", "crimson_stem"),
    ("crimson_hyphae", "crimson_hyphae"),
    ("crimson_roots", "crimson_roots"),
    ("warped_wart_block", "warped_wart_block"),
    ("nether_wart_block", "nether_wart_block"),
    ("weeping_vines", "weeping_vines"),
    ("red_mushroom_block", "red_mushroom_block"),
    ("brown_mushroom_block", "brown_mushroom_block"),
    ("mushroom_stem", "mushroom_stem"),
    ("shroomlight", "shroomlight"),
    ("iron_block", "iron_block"),
    ("copper_block", "copper_block"),
    ("weathered_copper", "weathered_copper"),
    ("diamond_block", "diamond_block"),
    ("emerald_block", "emerald_block"),
    ("quartz_block", "quartz_block"),
    ("smooth_quartz", "smooth_quartz"),
    ("quartz_stairs", "quartz_stairs"),
    ("amethyst_block", "amethyst_block"),
    ("amethyst_cluster", "amethyst_cluster"),
    ("budding_amethyst", "budding_amethyst"),
    ("emerald_ore", "emerald_ore"),
    ("deepslate_emerald_ore", "deepslate_emerald_ore"),
    ("obsidian", "obsidian"),
    ("crying_obsidian", "crying_obsidian"),
    ("lodestone", "lodestone"),
    ("chiseled_deepslate", "chiseled_deepslate"),
    ("deepslate_bricks", "deepslate_bricks"),
    ("stone_bricks", "stone_bricks"),
    ("chiseled_stone_bricks", "chiseled_stone_bricks"),
    ("cracked_stone_bricks", "cracked_stone_bricks"),
    ("mossy_stone_bricks", "mossy_stone_bricks"),
    ("smooth_stone_slab", "smooth_stone_slab"),
    ("stone_brick_slab", "stone_brick_slab"),
    ("stone_brick_stairs", "stone_brick_stairs"),
    ("warped_planks", "warped_planks"),
    ("end_stone", "end_stone"),
    ("white_wool", "white_wool"),
    ("red_wool", "red_wool"),
    ("black_wool", "black_wool"),
    ("white_concrete", "white_concrete"),
    ("black_concrete", "black_concrete"),
    ("red_concrete", "red_concrete"),
    ("light_blue_concrete", "light_blue_concrete"),
    ("gray_concrete", "gray_concrete"),
    ("light_gray_concrete", "light_gray_concrete"),
    ("soul_lantern", "soul_lantern"),
    ("redstone_lamp", "redstone_lamp"),
    ("verdant_froglight", "verdant_froglight"),
    ("cyan_stained_glass", "cyan_stained_glass"),
    ("light_blue_stained_glass", "light_blue_stained_glass"),
    ("blue_stained_glass", "blue_stained_glass"),
    ("glass", "glass"),
    ("tinted_glass", "tinted_glass"),
    ("glow_lichen", "glow_lichen"),
    ("sculk", "sculk"),
    ("sculk_vein", "sculk_vein"),
    ("dripstone_block", "dripstone_block"),
    ("pointed_dripstone", "pointed_dripstone"),
    ("lily_pad", "lily_pad"),
    ("sugar_cane", "sugar_cane"),
    ("tall_grass", "tall_grass"),
    ("fern", "fern"),
    ("dandelion", "dandelion"),
    ("poppy", "poppy"),
    ("peony", "peony"),
    ("pink_tulip", "pink_tulip"),
    ("pink_petals", "pink_petals"),
    ("lily_of_the_valley", "lily_of_the_valley"),
    ("sweet_berry_bush", "sweet_berry_bush"),
    ("prismarine", "prismarine"),
    ("tube_coral_block", "tube_coral_block"),
    ("oak_sign", "oak_sign"),
    ("spruce_sign", "spruce_sign"),
    ("birch_sign", "birch_sign"),
    ("dark_oak_sign", "dark_oak_sign"),
    ("farmland", "farmland"),
    ("wheat", "wheat"),
    ("potatoes", "potatoes"),
    ("carrots", "carrots"),
    ("beetroots", "beetroots"),
    (
        "chiseled_polished_blackstone",
        "chiseled_polished_blackstone",
    ),
    ("polished_blackstone", "polished_blackstone"),
    ("polished_blackstone_bricks", "polished_blackstone_bricks"),
    (
        "cracked_polished_blackstone_bricks",
        "cracked_polished_blackstone_bricks",
    ),
    ("nether_bricks", "nether_bricks"),
    ("red_nether_bricks", "red_nether_bricks"),
    ("end_stone_bricks", "end_stone_bricks"),
    ("purpur_block", "purpur_block"),
    ("lectern", "lectern"),
    ("wither_skeleton_skull", "wither_skeleton_skull"),
    ("skeleton_skull", "skeleton_skull"),
    ("barrel", "barrel"),
    ("crafting_table", "crafting_table"),
    ("furnace", "furnace"),
    ("brewing_stand", "brewing_stand"),
    ("cauldron", "cauldron"),
    ("bookshelf", "bookshelf"),
    ("chiseled_bookshelf", "chiseled_bookshelf"),
    ("chest", "chest"),
    ("trapped_chest", "trapped_chest"),
    ("iron_bars", "iron_bars"),
    ("raw_iron_block", "raw_iron_block"),
    ("chain", "chain"),
    ("lantern", "lantern"),
    ("end_rod", "end_rod"),
    ("lightning_rod", "lightning_rod"),
    ("sea_lantern", "sea_lantern"),
    ("glowstone", "glowstone"),
    ("glowshroom", "shroomlight"),
    ("air", "air"),
    ("cave_air", "cave_air"),
    ("smooth_basalt", "smooth_basalt"),
    ("polished_deepslate", "polished_deepslate"),
    ("polished_deepslate_slab", "polished_deepslate_slab"),
    ("deepslate_brick_slab", "deepslate_brick_slab"),
    ("cracked_deepslate_bricks", "cracked_deepslate_bricks"),
    ("water", "water"),
    ("vine", "vine"),
    ("dark_oak_planks", "dark_oak_planks"),
    ("oak_planks", "oak_planks"),
    ("spruce_planks", "spruce_planks"),
    ("dark_oak_slab", "dark_oak_slab"),
    ("dark_oak_stairs", "dark_oak_stairs"),
    ("polished_blackstone_slab", "polished_blackstone_slab"),
    ("polished_blackstone_stairs", "polished_blackstone_stairs"),
    ("polished_blackstone_wall", "polished_blackstone_wall"),
    ("purple_terracotta", "purple_terracotta"),
    ("purple_glazed_terracotta", "purple_glazed_terracotta"),
    ("purple_stained_glass", "purple_stained_glass"),
    ("purple_stained_glass_pane", "purple_stained_glass_pane"),
    ("campfire", "campfire"),
    ("soul_campfire", "soul_campfire"),
    ("candle", "candle"),
    ("coal_block", "coal_block"),
    ("coal_ore", "coal_ore"),
    ("cut_copper", "cut_copper"),
    ("raw_copper_block", "raw_copper_block"),
    ("flower_pot", "flower_pot"),
    ("birch_pressure_plate", "birch_pressure_plate"),
    ("oak_fence", "oak_fence"),
    ("red_mushroom", "red_mushroom"),
    ("brown_mushroom", "brown_mushroom"),
    ("warped_roots", "warped_roots"),
    ("twisting_vines", "twisting_vines"),
    ("bamboo", "bamboo"),
    ("small_amethyst_bud", "small_amethyst_bud"),
    ("white_banner", "white_banner"),
    ("iron_nugget", "air"),
];

pub(crate) fn legacy_block_state(name: &str) -> Option<BlockState> {
    match name {
        "stone" => Some(BlockState::STONE),
        "smooth_stone" => Some(BlockState::SMOOTH_STONE),
        "coarse_dirt" => Some(BlockState::COARSE_DIRT),
        "gravel" => Some(BlockState::GRAVEL),
        "grass_block" => Some(BlockState::GRASS_BLOCK),
        "dirt" => Some(BlockState::DIRT),
        "sand" => Some(BlockState::SAND),
        "sandstone" => Some(BlockState::SANDSTONE),
        "red_sandstone" => Some(BlockState::RED_SANDSTONE),
        "red_sand" => Some(BlockState::RED_SAND),
        "chiseled_red_sandstone" => Some(BlockState::CHISELED_RED_SANDSTONE),
        "terracotta" => Some(BlockState::TERRACOTTA),
        "red_terracotta" => Some(BlockState::RED_TERRACOTTA),
        "blackstone" => Some(BlockState::BLACKSTONE),
        "basalt" => Some(BlockState::BASALT),
        "polished_basalt" => Some(BlockState::POLISHED_BASALT),
        "magma_block" => Some(BlockState::MAGMA_BLOCK),
        "crimson_nylium" => Some(BlockState::CRIMSON_NYLIUM),
        "calcite" => Some(BlockState::CALCITE),
        "snow_block" => Some(BlockState::SNOW_BLOCK),
        "packed_ice" => Some(BlockState::PACKED_ICE),
        "blue_ice" => Some(BlockState::BLUE_ICE),
        "podzol" => Some(BlockState::PODZOL),
        "rooted_dirt" => Some(BlockState::ROOTED_DIRT),
        "soul_sand" => Some(BlockState::SOUL_SAND),
        "soul_soil" => Some(BlockState::SOUL_SOIL),
        "bone_block" => Some(BlockState::BONE_BLOCK),
        "mud" => Some(BlockState::MUD),
        "clay" => Some(BlockState::CLAY),
        "moss_block" => Some(BlockState::MOSS_BLOCK),
        "moss_carpet" => Some(BlockState::MOSS_CARPET),
        "andesite" => Some(BlockState::ANDESITE),
        "polished_andesite" => Some(BlockState::POLISHED_ANDESITE),
        "polished_diorite" => Some(BlockState::POLISHED_DIORITE),
        "deepslate" => Some(BlockState::DEEPSLATE),
        "cobbled_deepslate" => Some(BlockState::COBBLED_DEEPSLATE),
        "tuff" => Some(BlockState::TUFF),
        "cobblestone" => Some(BlockState::COBBLESTONE),
        "mossy_cobblestone" => Some(BlockState::MOSSY_COBBLESTONE),
        "dead_bush" => Some(BlockState::DEAD_BUSH),
        "grass" => Some(BlockState::GRASS),
        "cobweb" => Some(BlockState::COBWEB),
        "gray_concrete_powder" => Some(BlockState::GRAY_CONCRETE_POWDER),
        "cobblestone_wall" => Some(BlockState::COBBLESTONE_WALL),
        "torch" => Some(BlockState::TORCH),
        "stone_button" => Some(BlockState::STONE_BUTTON),
        "muddy_mangrove_roots" => Some(BlockState::MUDDY_MANGROVE_ROOTS),
        "oak_log" => Some(BlockState::OAK_LOG),
        "stripped_oak_log" => Some(BlockState::STRIPPED_OAK_LOG),
        "oak_leaves" => Some(BlockState::OAK_LEAVES),
        "birch_log" => Some(BlockState::BIRCH_LOG),
        "birch_leaves" => Some(BlockState::BIRCH_LEAVES),
        "stripped_birch_log" => Some(BlockState::STRIPPED_BIRCH_LOG),
        "spruce_log" => Some(BlockState::SPRUCE_LOG),
        "spruce_leaves" => Some(BlockState::SPRUCE_LEAVES),
        "stripped_spruce_log" => Some(BlockState::STRIPPED_SPRUCE_LOG),
        "jungle_log" => Some(BlockState::JUNGLE_LOG),
        "azalea_leaves" => Some(BlockState::AZALEA_LEAVES),
        "flowering_azalea_leaves" => Some(BlockState::FLOWERING_AZALEA_LEAVES),
        "mangrove_log" => Some(BlockState::MANGROVE_LOG),
        "mangrove_leaves" => Some(BlockState::MANGROVE_LEAVES),
        "mangrove_roots" => Some(BlockState::MANGROVE_ROOTS),
        "bamboo_block" => Some(BlockState::BAMBOO_BLOCK),
        "stripped_bamboo_block" => Some(BlockState::STRIPPED_BAMBOO_BLOCK),
        "crimson_stem" => Some(BlockState::CRIMSON_STEM),
        "crimson_hyphae" => Some(BlockState::CRIMSON_HYPHAE),
        "crimson_roots" => Some(BlockState::CRIMSON_ROOTS),
        "warped_wart_block" => Some(BlockState::WARPED_WART_BLOCK),
        "nether_wart_block" => Some(BlockState::NETHER_WART_BLOCK),
        "weeping_vines" => Some(BlockState::WEEPING_VINES),
        "red_mushroom_block" => Some(BlockState::RED_MUSHROOM_BLOCK),
        "brown_mushroom_block" => Some(BlockState::BROWN_MUSHROOM_BLOCK),
        "mushroom_stem" => Some(BlockState::MUSHROOM_STEM),
        "shroomlight" => Some(BlockState::SHROOMLIGHT),
        "iron_block" => Some(BlockState::IRON_BLOCK),
        "copper_block" => Some(BlockState::COPPER_BLOCK),
        "weathered_copper" => Some(BlockState::WEATHERED_COPPER),
        "diamond_block" => Some(BlockState::DIAMOND_BLOCK),
        "emerald_block" => Some(BlockState::EMERALD_BLOCK),
        "quartz_block" => Some(BlockState::QUARTZ_BLOCK),
        "smooth_quartz" => Some(BlockState::SMOOTH_QUARTZ),
        "quartz_stairs" => Some(BlockState::QUARTZ_STAIRS),
        "amethyst_block" => Some(BlockState::AMETHYST_BLOCK),
        "amethyst_cluster" => Some(BlockState::AMETHYST_CLUSTER),
        "budding_amethyst" => Some(BlockState::BUDDING_AMETHYST),
        "emerald_ore" => Some(BlockState::EMERALD_ORE),
        "deepslate_emerald_ore" => Some(BlockState::DEEPSLATE_EMERALD_ORE),
        "obsidian" => Some(BlockState::OBSIDIAN),
        "crying_obsidian" => Some(BlockState::CRYING_OBSIDIAN),
        "lodestone" => Some(BlockState::LODESTONE),
        "chiseled_deepslate" => Some(BlockState::CHISELED_DEEPSLATE),
        "deepslate_bricks" => Some(BlockState::DEEPSLATE_BRICKS),
        "stone_bricks" => Some(BlockState::STONE_BRICKS),
        "chiseled_stone_bricks" => Some(BlockState::CHISELED_STONE_BRICKS),
        "cracked_stone_bricks" => Some(BlockState::CRACKED_STONE_BRICKS),
        "mossy_stone_bricks" => Some(BlockState::MOSSY_STONE_BRICKS),
        "smooth_stone_slab" => Some(BlockState::SMOOTH_STONE_SLAB),
        "stone_brick_slab" => Some(BlockState::STONE_BRICK_SLAB),
        "stone_brick_stairs" => Some(BlockState::STONE_BRICK_STAIRS),
        "warped_planks" => Some(BlockState::WARPED_PLANKS),
        "end_stone" => Some(BlockState::END_STONE),
        "white_wool" => Some(BlockState::WHITE_WOOL),
        "red_wool" => Some(BlockState::RED_WOOL),
        "black_wool" => Some(BlockState::BLACK_WOOL),
        "white_concrete" => Some(BlockState::WHITE_CONCRETE),
        "black_concrete" => Some(BlockState::BLACK_CONCRETE),
        "red_concrete" => Some(BlockState::RED_CONCRETE),
        "light_blue_concrete" => Some(BlockState::LIGHT_BLUE_CONCRETE),
        "gray_concrete" => Some(BlockState::GRAY_CONCRETE),
        "light_gray_concrete" => Some(BlockState::LIGHT_GRAY_CONCRETE),
        "soul_lantern" => Some(BlockState::SOUL_LANTERN),
        "redstone_lamp" => Some(BlockState::REDSTONE_LAMP),
        "verdant_froglight" => Some(BlockState::VERDANT_FROGLIGHT),
        "cyan_stained_glass" => Some(BlockState::CYAN_STAINED_GLASS),
        "light_blue_stained_glass" => Some(BlockState::LIGHT_BLUE_STAINED_GLASS),
        "blue_stained_glass" => Some(BlockState::BLUE_STAINED_GLASS),
        "glass" => Some(BlockState::GLASS),
        "tinted_glass" => Some(BlockState::TINTED_GLASS),
        "glow_lichen" => Some(BlockState::GLOW_LICHEN),
        "sculk" => Some(BlockState::SCULK),
        "sculk_vein" => Some(BlockState::SCULK_VEIN),
        "dripstone_block" => Some(BlockState::DRIPSTONE_BLOCK),
        "pointed_dripstone" => Some(BlockState::POINTED_DRIPSTONE),
        "lily_pad" => Some(BlockState::LILY_PAD),
        "sugar_cane" => Some(BlockState::SUGAR_CANE),
        "tall_grass" => Some(BlockState::TALL_GRASS),
        "fern" => Some(BlockState::FERN),
        "dandelion" => Some(BlockState::DANDELION),
        "poppy" => Some(BlockState::POPPY),
        "peony" => Some(BlockState::PEONY),
        "pink_tulip" => Some(BlockState::PINK_TULIP),
        "pink_petals" => Some(BlockState::PINK_PETALS),
        "lily_of_the_valley" => Some(BlockState::LILY_OF_THE_VALLEY),
        "sweet_berry_bush" => Some(BlockState::SWEET_BERRY_BUSH),
        "prismarine" => Some(BlockState::PRISMARINE),
        "tube_coral_block" => Some(BlockState::TUBE_CORAL_BLOCK),
        "oak_sign" => Some(BlockState::OAK_SIGN),
        "spruce_sign" => Some(BlockState::SPRUCE_SIGN),
        "birch_sign" => Some(BlockState::BIRCH_SIGN),
        "dark_oak_sign" => Some(BlockState::DARK_OAK_SIGN),
        "farmland" => Some(BlockState::FARMLAND),
        "wheat" => Some(BlockState::WHEAT),
        "potatoes" => Some(BlockState::POTATOES),
        "carrots" => Some(BlockState::CARROTS),
        "beetroots" => Some(BlockState::BEETROOTS),
        "chiseled_polished_blackstone" => Some(BlockState::CHISELED_POLISHED_BLACKSTONE),
        "polished_blackstone" => Some(BlockState::POLISHED_BLACKSTONE),
        "polished_blackstone_bricks" => Some(BlockState::POLISHED_BLACKSTONE_BRICKS),
        "cracked_polished_blackstone_bricks" => {
            Some(BlockState::CRACKED_POLISHED_BLACKSTONE_BRICKS)
        }
        "nether_bricks" => Some(BlockState::NETHER_BRICKS),
        "red_nether_bricks" => Some(BlockState::RED_NETHER_BRICKS),
        "end_stone_bricks" => Some(BlockState::END_STONE_BRICKS),
        "purpur_block" => Some(BlockState::PURPUR_BLOCK),
        "lectern" => Some(BlockState::LECTERN),
        "wither_skeleton_skull" => Some(BlockState::WITHER_SKELETON_SKULL),
        "skeleton_skull" => Some(BlockState::SKELETON_SKULL),
        "barrel" => Some(BlockState::BARREL),
        "crafting_table" => Some(BlockState::CRAFTING_TABLE),
        "furnace" => Some(BlockState::FURNACE),
        "brewing_stand" => Some(BlockState::BREWING_STAND),
        "cauldron" => Some(BlockState::CAULDRON),
        "bookshelf" => Some(BlockState::BOOKSHELF),
        "chiseled_bookshelf" => Some(BlockState::CHISELED_BOOKSHELF),
        "chest" => Some(BlockState::CHEST),
        "trapped_chest" => Some(BlockState::TRAPPED_CHEST),
        "iron_bars" => Some(BlockState::IRON_BARS),
        "raw_iron_block" => Some(BlockState::RAW_IRON_BLOCK),
        "chain" => Some(BlockState::CHAIN),
        "lantern" => Some(BlockState::LANTERN),
        "end_rod" => Some(BlockState::END_ROD),
        "lightning_rod" => Some(BlockState::LIGHTNING_ROD),
        "sea_lantern" => Some(BlockState::SEA_LANTERN),
        "glowstone" => Some(BlockState::GLOWSTONE),
        "air" => Some(BlockState::AIR),
        "cave_air" => Some(BlockState::CAVE_AIR),
        "smooth_basalt" => Some(BlockState::SMOOTH_BASALT),
        "polished_deepslate" => Some(BlockState::POLISHED_DEEPSLATE),
        "polished_deepslate_slab" => Some(BlockState::POLISHED_DEEPSLATE_SLAB),
        "deepslate_brick_slab" => Some(BlockState::DEEPSLATE_BRICK_SLAB),
        "cracked_deepslate_bricks" => Some(BlockState::CRACKED_DEEPSLATE_BRICKS),
        "water" => Some(BlockState::WATER),
        "vine" => Some(BlockState::VINE),
        "dark_oak_planks" => Some(BlockState::DARK_OAK_PLANKS),
        "oak_planks" => Some(BlockState::OAK_PLANKS),
        "spruce_planks" => Some(BlockState::SPRUCE_PLANKS),
        "dark_oak_slab" => Some(BlockState::DARK_OAK_SLAB),
        "dark_oak_stairs" => Some(BlockState::DARK_OAK_STAIRS),
        "polished_blackstone_slab" => Some(BlockState::POLISHED_BLACKSTONE_SLAB),
        "polished_blackstone_stairs" => Some(BlockState::POLISHED_BLACKSTONE_STAIRS),
        "polished_blackstone_wall" => Some(BlockState::POLISHED_BLACKSTONE_WALL),
        "purple_terracotta" => Some(BlockState::PURPLE_TERRACOTTA),
        "purple_glazed_terracotta" => Some(BlockState::PURPLE_GLAZED_TERRACOTTA),
        "purple_stained_glass" => Some(BlockState::PURPLE_STAINED_GLASS),
        "purple_stained_glass_pane" => Some(BlockState::PURPLE_STAINED_GLASS_PANE),
        "campfire" => Some(BlockState::CAMPFIRE),
        "soul_campfire" => Some(BlockState::SOUL_CAMPFIRE),
        "candle" => Some(BlockState::CANDLE),
        "coal_block" => Some(BlockState::COAL_BLOCK),
        "coal_ore" => Some(BlockState::COAL_ORE),
        "cut_copper" => Some(BlockState::CUT_COPPER),
        "raw_copper_block" => Some(BlockState::RAW_COPPER_BLOCK),
        "flower_pot" => Some(BlockState::FLOWER_POT),
        "birch_pressure_plate" => Some(BlockState::BIRCH_PRESSURE_PLATE),
        "oak_fence" => Some(BlockState::OAK_FENCE),
        "red_mushroom" => Some(BlockState::RED_MUSHROOM),
        "brown_mushroom" => Some(BlockState::BROWN_MUSHROOM),
        "warped_roots" => Some(BlockState::WARPED_ROOTS),
        "twisting_vines" => Some(BlockState::TWISTING_VINES),
        "bamboo" => Some(BlockState::BAMBOO),
        "small_amethyst_bud" => Some(BlockState::SMALL_AMETHYST_BUD),
        "white_banner" => Some(BlockState::WHITE_BANNER),
        "glowshroom" => Some(BlockState::SHROOMLIGHT),
        "iron_nugget" => Some(BlockState::AIR),
        _ => None,
    }
}
